#!/bin/ksh
test -f .SsmDepot && SsmDepot=$(cat .SsmDepot)
package=${0#./}
package=${package%%/*}
echo package=$package
TarCmd="echo tar"
tar --help 1>/dev/null 2>/dev/null && TarCmd=tar
gtar --help 1>/dev/null 2>/dev/null && TarCmd=gtar
gnutar --help 1>/dev/null 2>/dev/null && TarCmd=gnutar
set -x
${TarCmd} $(cat ${package}/maint/excludes) --exclude-from=${package}/maint/excludes.list -zcf ${SsmDepot}/${package}.ssm $(cat ${package}/maint/include)
