OBJS =  mw_vacos.o      mw_verfc.o      mw_vpopcnt8.o   mw_vsatanh.o    mw_vsin.o       mw_vsrec.o \
	mw_vacosh.o     mw_vexp.o       mw_vpow.o       mw_vscbrt.o     mw_vsincos.o    mw_vsrqdrt.o \
	mw_vasin.o      mw_vexp2.o      mw_vqdrt.o      mw_vscos.o      mw_vsinh.o      mw_vsrsqrt.o \
	mw_vasinh.o     mw_vexp2m1.o    mw_vrcbrt.o     mw_vscosh.o     mw_vslgamma.o   mw_vssin.o \
	mw_vatan.o      mw_vexpm1.o     mw_vrec.o       mw_vscosisin.o  mw_vslog.o      mw_vssincos.o \
	mw_vatan2.o     mw_vhypot.o     mw_vrqdrt.o     mw_vsdiv.o      mw_vslog10.o    mw_vssinh.o \
	mw_vatanh.o     mw_vlgamma.o    mw_vrsqrt.o     mw_vserf.o      mw_vslog1p.o    mw_vssqrt.o \
	mw_vcbrt.o      mw_vlog.o       mw_vsacos.o     mw_vserfc.o     mw_vslog2.o     mw_vstan.o \
	mw_vcos.o       mw_vlog10.o     mw_vsacosh.o    mw_vsexp.o      mw_vslog21p.o   mw_vstanh.o \
	mw_vcosh.o      mw_vlog1p.o     mw_vsasin.o     mw_vsexp2.o     mw_vspow.o      mw_vtan.o \
	mw_vcosisin.o   mw_vlog2.o      mw_vsasinh.o    mw_vsexp2m1.o   mw_vsqdrt.o     mw_vtanh.o \
	mw_vdiv.o       mw_vlog21p.o    mw_vsatan.o     mw_vsexpm1.o    mw_vsqrt.o      mw_verf.o \
	mw_vpopcnt4.o   mw_vsatan2.o    mw_vshypot.o    mw_vsrcbrt.o \
	mw_vacos_2d.o      mw_verfc_2d.o      mw_vpopcnt8_2d.o   mw_vsatanh_2d.o    mw_vsin_2d.o       mw_vsrec_2d.o \
	mw_vacosh_2d.o     mw_vexp_2d.o       mw_vpow_2d.o       mw_vscbrt_2d.o     mw_vsincos_2d.o    mw_vsrqdrt_2d.o \
	mw_vasin_2d.o      mw_vexp2_2d.o      mw_vqdrt_2d.o      mw_vscos_2d.o      mw_vsinh_2d.o      mw_vsrsqrt_2d.o \
	mw_vasinh_2d.o     mw_vexp2m1_2d.o    mw_vrcbrt_2d.o     mw_vscosh_2d.o     mw_vslgamma_2d.o   mw_vssin_2d.o \
	mw_vatan_2d.o      mw_vexpm1_2d.o     mw_vrec_2d.o       mw_vscosisin_2d.o  mw_vslog_2d.o      mw_vssincos_2d.o \
	mw_vatan2_2d.o     mw_vhypot_2d.o     mw_vrqdrt_2d.o     mw_vsdiv_2d.o      mw_vslog10_2d.o    mw_vssinh_2d.o \
	mw_vatanh_2d.o     mw_vlgamma_2d.o    mw_vrsqrt_2d.o     mw_vserf_2d.o      mw_vslog1p_2d.o    mw_vssqrt_2d.o \
	mw_vcbrt_2d.o      mw_vlog_2d.o       mw_vsacos_2d.o     mw_vserfc_2d.o     mw_vslog2_2d.o     mw_vstan_2d.o \
	mw_vcos_2d.o       mw_vlog10_2d.o     mw_vsacosh_2d.o    mw_vsexp_2d.o      mw_vslog21p_2d.o   mw_vstanh_2d.o \
	mw_vcosh_2d.o      mw_vlog1p_2d.o     mw_vsasin_2d.o     mw_vsexp2_2d.o     mw_vspow_2d.o      mw_vtan_2d.o \
	mw_vcosisin_2d.o   mw_vlog2_2d.o      mw_vsasinh_2d.o    mw_vsexp2m1_2d.o   mw_vsqdrt_2d.o     mw_vtanh_2d.o \
	mw_vdiv_2d.o       mw_vlog21p_2d.o    mw_vsatan_2d.o     mw_vsexpm1_2d.o    mw_vsqrt_2d.o      mw_verf_2d.o \
	mw_vpopcnt4_2d.o   mw_vsatan2_2d.o    mw_vshypot_2d.o    mw_vsrcbrt_2d.o \
	mw_vacos_s.o      mw_verfc_s.o      mw_vpopcnt8_s.o   mw_vsatanh_s.o    mw_vsin_s.o       mw_vsrec_s.o \
	mw_vacosh_s.o     mw_vexp_s.o       mw_vpow_s.o       mw_vscbrt_s.o     mw_vsincos_s.o    mw_vsrqdrt_s.o \
	mw_vasin_s.o      mw_vexp2_s.o      mw_vqdrt_s.o      mw_vscos_s.o      mw_vsinh_s.o      mw_vsrsqrt_s.o \
	mw_vasinh_s.o     mw_vexp2m1_s.o    mw_vrcbrt_s.o     mw_vscosh_s.o     mw_vslgamma_s.o   mw_vssin_s.o \
	mw_vatan_s.o      mw_vexpm1_s.o     mw_vrec_s.o       mw_vscosisin_s.o  mw_vslog_s.o      mw_vssincos_s.o \
	mw_vatan2_s.o     mw_vhypot_s.o     mw_vrqdrt_s.o     mw_vsdiv_s.o      mw_vslog10_s.o    mw_vssinh_s.o \
	mw_vatanh_s.o     mw_vlgamma_s.o    mw_vrsqrt_s.o     mw_vserf_s.o      mw_vslog1p_s.o    mw_vssqrt_s.o \
	mw_vcbrt_s.o      mw_vlog_s.o       mw_vsacos_s.o     mw_vserfc_s.o     mw_vslog2_s.o     mw_vstan_s.o \
	mw_vcos_s.o       mw_vlog10_s.o     mw_vsacosh_s.o    mw_vsexp_s.o      mw_vslog21p_s.o   mw_vstanh_s.o \
	mw_vcosh_s.o      mw_vlog1p_s.o     mw_vsasin_s.o     mw_vsexp2_s.o     mw_vspow_s.o      mw_vtan_s.o \
	mw_vcosisin_s.o   mw_vlog2_s.o      mw_vsasinh_s.o    mw_vsexp2m1_s.o   mw_vsqdrt_s.o     mw_vtanh_s.o \
	mw_vdiv_s.o       mw_vlog21p_s.o    mw_vsatan_s.o     mw_vsexpm1_s.o    mw_vsqrt_s.o      mw_verf_s.o \
	mw_vpopcnt4_s.o   mw_vsatan2_s.o    mw_vshypot_s.o    mw_vsrcbrt_s.o

wrapper=massvp7_wrap

.SUFFIXES: .f90 .o
.f90.o:
	r.compile -includes ./tmp -optf '=-qnoflttrap' -src $<
	#xlf90 -c -I./tmp $<

#%.o : %.f90
#	xlf90 -c -I./tmp $<

default: lib

lib: ../lib/lib$(wrapper).a

../lib/lib$(wrapper).a: $(wrapper).tmpl src
	$(MAKE) obj ;\
	ar -cru $@ *.o ;\
	rm -f *.o

src: $(wrapper).tmpl
	buildsrc $(wrapper)

obj: $(OBJS)

clean:
	rm -f *.o *.f90 

distclean: clean
	rm -f ../lib/lib$(wrapper).a