#!/bin/ksh
set -x
domainHome=$1
packageHome=$2
profileDirPath=${packageHome}/etc/profile.d
packageFullName=${packageHome##*/}
packageNameVersion=${packageFullName%_*}
packageName=${packageNameVersion%%_*}
packageVersion=${packageNameVersion##*_}
packageArch=${packageFullName##*_}
profilePath=${profileDirPath}/${packageFullName}.sh
mkdir -p ${profileDirPath}
cd ${packageHome}

mkdir bin 2>/dev/null
cp .ssm.d/r.pkg-config bin/r.${packageName}_${packageArch}-config

$packageHome/.ssm.d/post-install-lib $domainHome $packageHome
exitstatus=$?

if [[ x$exitstatus == x0 ]] ; then
	 $packageHome/.ssm.d/post-install-bin $domainHome $packageHome
	 exitstatus=$?
fi

exit $exitstatus
