#!/bin/ksh
set -x
domainHome=$1
packageHome=$2
profileDirPath=${packageHome}/etc/profile.d
packageFullName=${packageHome##*/}
packageNameVersion=${packageFullName%_*}
packageName=${packageNameVersion%%_*}
packageVersion=${packageNameVersion##*_}
profilePath=${profileDirPath}/${packageFullName}.sh
mkdir -p ${profileDirPath}
cd ${packageHome}

mkdir bin 2>/dev/null
cp .ssm.d/r.pkg-config bin/r.${packageName}_${packageFullName##*_}-config

#cat > $profilePath <<EOF
#export ATM_MODEL_BINDIR=$packageHome/bin/release
#EOF
#==== 

#$packageHome/.ssm.d/post-install-lib $domainHome $packageHome
#TODO: check if ok

$packageHome/.ssm.d/post-install-bin $domainHome $packageHome
exitstatus=$?

if [[ x$exitstatus != x0 ]] ; then
	 exit 1
fi
exit 0
