#!/bin/ksh
set -x
domainHome=$1
packageHome=$2
profileDirPath=${packageHome}/etc/profile.d
packageFullName=${packageHome##*/}
packageNameVersion=${packageFullName%_*}
packageName=${packageNameVersion%%_*}
packageVersion=${packageNameVersion##*_}
profilePath=${profileDirPath}/${packageFullName}.sh
mkdir -p ${profileDirPath}
cd ${packageHome}

#mkdir bin
#cp .ssm.d/r.pkg-config bin/r.${packageName}_${packageFullName##*_}-config

#==== Define needed vars in package profile
cat > ${profilePath} << EOF
#${packageName}_HOME=${packageHome}
#${packageName}_VERSION=${packageVersion}
#export gem=$packageHome
#export MODEL_PATH=$packageHome
#export ATM_MODEL_PATH=$packageHome
#export gem_VERSION=$packageVersion
#export FULL_MODEL=GEMDM
#export MODEL=gem
#export MODEL_VERSION=$packageVersion
#export ATM_MODEL=gem
export ATM_MODEL_VERSION=$packageVersion
export ATM_MODEL_BNDL=${ssm_bndl:-GEM/${ssm_bndl_x}${packageVersion}}
export ATM_MODEL_DSTP="$(date '+%Y-%m-%d %H:%M %Z')"
export PATH=\$HOME/modeles/GEMDM/v_${packageVersion}/bin:\$HOME/modeles/GEMDM/v_${packageVersion}/bin/\${BASE_ARCH}:\$PATH
EOF


#==== link back scripts and dfiles [for backward compatibility]
#TODO: remove this in future version (need scripts adjustments)
cd ${packageHome}
#scriptsdir=$(r.gem-scripts_all-config --bin 2>/dev/null)
#dfilesdir=$(r.gem-data-config --dfiles 2>/dev/null)
#[[ x$scriptsdir != x ]] && ln -s $(true_path $scriptsdir scripts)
#[[ x$dfilesdir  != x ]] && ln -s $(true_path $dfilesdir dfiles)



