#!/usr/bin/env ksh
domainHome=$1
packageHome=$2
profileDirPath=${packageHome}/etc/profile.d
packageName=${packageHome##*/}
profilePath=${profileDirPath}/${packageName}.sh
mkdir -p ${profileDirPath}
Platform=`uname -s` ; [[ $Platform = Linux ]] && Platform=${Platform}-`uname -m`
cp ${packageHome}/.ssm.d/profile.sh ${profilePath}
echo "export MAESTRO_CURRENT_REF=${packageHome}" >>${profilePath}
echo "alias gemdev='. gemdev.dot'" >>${profilePath}
chmod 644 ${profilePath}

# Set top level module paths in reference
if [[ -z "${MAESTRO_MODULE_DEPOT}" ]] ; then
  echo "Environment variable MAESTRO_MODULE_DEPOT (colon-separated path) must be set"
  exit 1
fi

# Process dependencies
${packageHome}/bin/process_deplist ${packageHome} ${MAESTRO_MODULE_DEPOT} ${packageHome}/etc/deplist

# Set data paths in experiment configuration file
expcfg=${packageHome}/ref/experiment
printf "# Added by SSM pre-publication script\nMAESTRO_PACKAGE_DATA=${packageHome}\n\n" >${expcfg}.cfg
cat ${expcfg}.tmpl >>${expcfg}.cfg
rm -f ${expcfg}.tmpl
