!-------------------------------------- LICENCE BEGIN ------------------------------------
!Environment Canada - Atmospheric Science and Technology License/Disclaimer, 
!                     version 3; Last Modified: May 7, 2008.
!This is free but copyrighted software; you can use/redistribute/modify it under the terms 
!of the Environment Canada - Atmospheric Science and Technology License/Disclaimer 
!version 3 or (at your option) any later version that should be found at: 
!http://collaboration.cmc.ec.gc.ca/science/rpn.comm/license.html 
!
!This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
!without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
!See the above mentioned License/Disclaimer for more details.
!You should have received a copy of the License/Disclaimer along with this software; 
!if not, you can write to: EC-RPN COMM Group, 2121 TransCanada, suite 500, Dorval (Quebec), 
!CANADA, H9P 1J3; or send e-mail to service.rpn@ec.gc.ca
!-------------------------------------- LICENCE END --------------------------------------

!/@*
subroutine phybusinit(n,nk)
   use phy_options
   use phybus
   implicit none
#include <arch_specific.hf>
   !@Object Establishes requirements in terms of variables in the 4 main buses 
   !        (busent, busdyn, busper and busvol) for the entire physics.
   !@Arguments
   integer, intent(in) ::  n,nk !# horiz and vert dimensions
   !@Author M. Desgagne (Oct 1995)

   !@Revision
   ! 001      L. Spacek  (Aug 2010) - Complete rewrite
   ! 002      B. Dugas   (Oct 2010) - A few small corrections
   ! 003      L. Spacek  (Sep 2011) - Eliminate obsolete convection options
   !*@/

#include <WhiteBoard.hf>
#include "ens.cdk"
#include "surface.cdk"
#include "mcica.cdk"
#include "clefcon.cdk"

   integer :: nmos=0 !#TODO: delete

   character(len=2)  :: nagg, nipt, nm, nmar, need_wz
   integer :: options, ier, tmp, iverb
   logical :: lcn_mpx,lcn_my2,lcn_p3i1,lcn_p3i2,lcn_p3i3,lcn_p3i4
   logical :: lbourg3d,lbourg
   logical :: lpblcpl
   logical :: lrslp
   logical :: lkfbe,lshal
   logical :: ladvtke,nadvtke,lmoistke
   logical :: lmoyhr,lmoyhrkf
   logical :: lccc2
   integer :: nsurf

   !---------------------------------------------------------------------

   options = WB_REWRITE_NONE+WB_IS_LOCAL
   iverb = wb_verbosity(WB_MSG_INFO)

   ier = WB_OK
   ier = min(wb_get('sfc/nsurf', nsurf), ier)
   ier = min(wb_get('sfc/schmsol', schmsol), ier)
   
   iverb = wb_verbosity(iverb)

   !# nagg is the dimension of aggregrated variables
   write(nagg,'(i2)') nsurf+1
      
   !# nipt is the number of tau/cloud top pressure bins in ISCCP histograms
   write(nipt,'(i2)') ntau*nptop
   
   !# nm is the number of mosaic 'layers'
   write(nm,'(i2)') nmos !#TODO: delete
   
   !# nmar is the number of 2d Markov fields
   write(nmar,'(i2)') (imrkv2)
   
   lcn_mpx  = (stcond(1:2) == 'MP')
   lcn_my2  = (stcond(1:6) == 'MP_MY2')
   lcn_p3i1 = (stcond == 'MP_P3' .and. mp_p3_ncat >= 1)
   lcn_p3i2 = (stcond == 'MP_P3' .and. mp_p3_ncat >= 2)
   lcn_p3i3 = (stcond == 'MP_P3' .and. mp_p3_ncat >= 3)
   lcn_p3i4 = (stcond == 'MP_P3' .and. mp_p3_ncat == 4)

   lbourg3d= (pcptype == 'BOURGE3D')
   lpblcpl = pbl_coupled
   lrslp   = radslope
   ladvtke = advectke
   nadvtke = .not.ladvtke
   lmoyhr  = (moyhr > 0 .or. dynout)
   lkfbe   = any(convec == (/'BECHTOLD','KFC     '/))
   lshal   = (conv_shal /= 'NIL')
   lmoyhrkf= (lmoyhr .and. lkfbe)
   lbourg  = any(pcptype == (/'BOURGE','NIL   '/))
   lmoistke= (fluvert == 'MOISTKE')
   lccc2   = (radia == 'CCCMARAD2')

   need_wz = '1'
   if (offline) need_wz = '0'

               call gesdict (n, nk, ae,           'VN=ae           ;ON=AE  ;VD=accum. of stratiform precip.                   ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, aip,          'VN=aip          ;ON=PE  ;VD=accum. of refrozen precip.                     ;VS=row                    ;VB=p0        ;MIN=0')
 if(lbourg3d)  call gesdict (n, nk, aip3d,        'VN=aip3d        ;ON=PE3D;VD=accum. of refrozen precip.3D                   ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, alc,          'VN=alc          ;ON=A1  ;VD=accum. of liquid convect. precip.              ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, alcs,         'VN=alcs         ;ON=A8  ;VD=accum. of liquid shall. convect. precip.       ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, alfaq,        'VN=alfaq        ;ON=AQ  ;VD=inhomog. term for Q diff.                      ;VS=row@'//nm//'           ;VB=v0')
               call gesdict (n, nk, alfat,        'VN=alfat        ;ON=AT  ;VD=inhomog. term for T diffu.                     ;VS=row@'//nm//'           ;VB=v0')
               call gesdict (n, nk, als,          'VN=als          ;ON=A2  ;VD=accum. of liquid precip, grid-scale cond       ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, als_fr1,      'VN=als_fr1      ;ON=FR1 ;VD=accum. freezing drizzle      (M-Y)             ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, als_fr2,      'VN=als_fr2      ;ON=FR2 ;VD=accum. freezing rain         (M-Y)             ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, als_rn1,      'VN=als_rn1      ;ON=RN1 ;VD=accum. liquid drizzle        (M-Y)             ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, als_rn2,      'VN=als_rn2      ;ON=RN2 ;VD=accum. liquid rain           (M-Y)             ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, alvis,        'VN=alvis        ;ON=AL  ;VD=visible surface albedo                         ;VS=row*'//nagg//'@'//nm//';VB=p0        ;MIN=0')
               call gesdict (n, nk, ap,           'VN=ap           ;ON=AP  ;VD=planetary albedo                               ;VS=row                    ;VB=v0        ;MIN=0')
 if(lkfbe)     call gesdict (n, nk, areaup,       'VN=areaup       ;ON=UA  ;VD=area of updraft (FCP)                          ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, asc,          'VN=asc          ;ON=A3  ;VD=accum. of solid  convect. precip.              ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, ascs,         'VN=ascs         ;ON=A9  ;VD=accum. of solid  shall. convect. precip.       ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, ass,          'VN=ass          ;ON=A4  ;VD=accum. of total solid precip, grid-scale cond  ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, ass_mx,       'VN=ass_mx       ;ON=AMX ;VD=accum. mixed pcp              (M-Y)            ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, ass_pe1,      'VN=ass_pe1      ;ON=PE1 ;VD=accum. ice pellets           (M-Y)             ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, ass_pe2,      'VN=ass_pe2      ;ON=PE2 ;VD=accum. hail (M-Y)                              ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, ass_pe2l,     'VN=ass_pe2l     ;ON=PE2L;VD=accum. large hail          (M-Y)               ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, ass_s2l,      'VN=ass_s2l      ;ON=S2L ;VD=solid:liquid ratio [SND/SN]  (M-Y)             ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, ass_sn1,      'VN=ass_sn1      ;ON=SN1 ;VD=accum. ice crystals          (M-Y)             ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, ass_sn2,      'VN=ass_sn2      ;ON=SN2 ;VD=accum. snow (M-Y)                              ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, ass_sn3,      'VN=ass_sn3      ;ON=SN3 ;VD=accum. graupel (M-Y)                           ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, ass_snd,      'VN=ass_snd      ;ON=SND ;VD=accum. total unmelted snow (micro)             ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, at2e,         'VN=at2e         ;ON=AT2E;VD=weights T,Q to enrg                            ;VS=slb                    ;VB=v0')
               call gesdict (n, nk, at2m,         'VN=at2m         ;ON=AT2M;VD=weights T,Q to mom                             ;VS=slb                    ;VB=v0')
               call gesdict (n, nk, at2t,         'VN=at2t         ;ON=AT2T;VD=weights T,Q to thermo                          ;VS=slb                    ;VB=v0')
               call gesdict (n, nk, au2t,         'VN=au2t         ;ON=AU2T;VD=weights PHI,U,V to thermo                      ;VS=slb                    ;VB=v0')
               call gesdict (n, nk, azr,          'VN=azr          ;ON=FR  ;VD=accum. of freezg precip.                       ;VS=row                    ;VB=p0        ;MIN=0')
 if(lbourg3d)  call gesdict (n, nk, azr3d,        'VN=azr3d        ;ON=FR3D;VD=accum. of freezg precip. 3D                    ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, basc,         'VN=basc         ;ON=BS  ;VD=base sigma of condensation level               ;VS=row                    ;VB=v0')
               call gesdict (n, nk, bm,           'VN=bm           ;ON=BM  ;VD=homog. term for U,V diffu.                     ;VS=row@'//nm//'           ;VB=v0')
               call gesdict (n, nk, bt,           'VN=bt           ;ON=BT  ;VD=homog. term for T,Q diffu.                     ;VS=row*'//nagg//'@'//nm//';VB=v0')
               call gesdict (n, nk, tdmask,       'VN=tdmask       ;ON=MPTD;VD=Horizontal weight for tendency application     ;VS=row                    ;VB=p0')
 if(lrslp)     call gesdict (n, nk, c1slop,       'VN=C1SL         ;ON=C1SL;VD=C1 for radslope                                ;VS=row                    ;VB=p0')
 if(lrslp)     call gesdict (n, nk, c2slop,       'VN=C2SL         ;ON=C2SL;VD=C2 for radslope                                ;VS=row                    ;VB=p0')
 if(lrslp)     call gesdict (n, nk, c3slop,       'VN=C3SL         ;ON=C3SL;VD=C3 for radslope                                ;VS=row                    ;VB=p0')
 if(lrslp)     call gesdict (n, nk, c4slop,       'VN=C4SL         ;ON=C4SL;VD=C4 for radslope                                ;VS=row                    ;VB=p0')
 if(lrslp)     call gesdict (n, nk, c5slop,       'VN=C5SL         ;ON=C5SL;VD=C5 for radslope                                ;VS=row                    ;VB=p0')
               call gesdict (n, nk, cang,         'VN=cang         ;ON=CX  ;VD=cosine of the solar angle                      ;VS=row                    ;VB=v0')
 if(lkfbe)     call gesdict (n, nk, capekfc,      'VN=capekfc      ;ON=U4  ;VD=CAPE calculated in KF                          ;VS=row                    ;VB=p0        ;MIN=0')
 if(lmoyhrkf)  call gesdict (n, nk, capekfcm,     'VN=capekfcm     ;ON=6K  ;VD=avg capekfc                                    ;VS=row                    ;VB=p0        ;MIN=0')
 if(lmoyhr)    call gesdict (n, nk, ccnm,         'VN=ccnm         ;ON=CA  ;VD=total clouds avge over last moyhr hrs          ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, clb,          'VN=clb          ;ON=CLB ;VD=net clear sky lw flux at sfc                   ;VS=row                    ;VB=p0')
               call gesdict (n, nk, clbaf,        'VN=clbaf        ;ON=ACLB;VD=accumulation of clb                            ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, cldrad,       'VN=cldrad       ;ON=CLDR;VD=cloud for radiation                            ;VS=slc                    ;VB=v0        ;MIN=0')
 if(lmoyhr)    call gesdict (n, nk, cldradm,      'VN=cldradm      ;ON=CLRM;VD=total clouds for rad avg over last moyhr hours ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, clr,          'VN=clr          ;ON=13  ;VD=cloud rain kg/m3 (condensation)                ;VS=slc                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, cls,          'VN=cls          ;ON=NN  ;VD=cloud snow kg/m3 (condensation)                ;VS=slc                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, clt,          'VN=clt          ;ON=CLT ;VD=net clear sky lw flux at top                   ;VS=row                    ;VB=p0')
               call gesdict (n, nk, cltaf,        'VN=cltaf        ;ON=ACLT;VD=accumulation of clt                            ;VS=row                    ;VB=p0')
               call gesdict (n, nk, cosas,        'VN=cosas        ;ON=CO  ;VD=cosine of the solar angle for averaging        ;VS=row                    ;VB=p0')
               call gesdict (n, nk, cosz,         'VN=cosz         ;ON=M4  ;VD=cosine of the solar angle                      ;VS=row                    ;VB=p0')
               call gesdict (n, nk, cqe,          'VN=cqe          ;ON=CQE ;VD=conv. Q tendency                               ;VS=slc                    ;VB=v0')
               call gesdict (n, nk, csb,          'VN=csb          ;ON=CSB ;VD=net clear sky solar flux at sfc                ;VS=row                    ;VB=p0')
               call gesdict (n, nk, csbaf,        'VN=csbaf        ;ON=ACSB;VD=accumulation of csb                            ;VS=row                    ;VB=p0')
               call gesdict (n, nk, cstaf,        'VN=cstaf        ;ON=ACST;VD=accumulation of cstt                           ;VS=row                    ;VB=p0')
               call gesdict (n, nk, cstt,         'VN=cstt         ;ON=CSTT;VD=net clear sky solar flux at top                ;VS=row                    ;VB=p0')
               call gesdict (n, nk, cte,          'VN=cte          ;ON=CTE ;VD=conv. T tendency                               ;VS=slc                    ;VB=v0')
               call gesdict (n, nk, ctp,          'VN=ctp          ;ON=BP  ;VD=cloud top pressure                             ;VS=row                    ;VB=v0')
               call gesdict (n, nk, ctt,          'VN=ctt          ;ON=BE  ;VD=cloud top temperature                          ;VS=row                    ;VB=v0')
               call gesdict (n, nk, ctue,         'VN=ctue         ;ON=CH  ;VD=transfert coeff. for thermo.(m/s)              ;VS=row                    ;VB=v0')
 if(refract)   call gesdict (n, nk, dct_bh,       'VN=dct_bh       ;ON=DCBH;VD=duct base height (IR/RF)                       ;VS=row                    ;VB=v0')
 if(refract)   call gesdict (n, nk, dct_count,    'VN=dct_nb       ;ON=DCNB;VD=number of ducts (IR/RF)                        ;VS=row                    ;VB=v0')
 if(refract)   call gesdict (n, nk, dct_lvl,      'VN=dct_lvl      ;ON=DCLL;VD=duct info level (IR/RF)                        ;VS=row                    ;VB=v0')
 if(refract)   call gesdict (n, nk, dct_lvlmax,   'VN=dct_lvlmax   ;ON=DC1M;VD=level of the first local max (IR/RF)           ;VS=row                    ;VB=v0')
 if(refract)   call gesdict (n, nk, dct_lvlmin,   'VN=dct_lvlmin   ;ON=DC1I;VD=level of the first local min (IR/RF)           ;VS=row                    ;VB=v0')
 if(refract)   call gesdict (n, nk, dct_moref,    'VN=dct_moref    ;ON=DCMR;VD=modified refractivity (IR/RF)                  ;VS=slb                    ;VB=v0')
 if(refract)   call gesdict (n, nk, dct_sndmax,   'VN=dct_sndmax   ;ON=DC2M;VD=level of the second local max (IR/RF)          ;VS=row                    ;VB=v0')
 if(refract)   call gesdict (n, nk, dct_sndmin,   'VN=dct_sndmin   ;ON=DC2I;VD=level of the second local min (IR/RF)          ;VS=row                    ;VB=v0')
 if(refract)   call gesdict (n, nk, dct_str,      'VN=dct_str      ;ON=DCST;VD=duct strength (IR/RF)                          ;VS=row                    ;VB=v0')
 if(refract)   call gesdict (n, nk, dct_thick,    'VN=dct_thick    ;ON=DCTH;VD=duct thickness (IR/RF)                         ;VS=row                    ;VB=v0')
 if(refract)   call gesdict (n, nk, dct_trdmax,   'VN=dct_trdmax   ;ON=DC3M;VD=level of the third local max (IR/RF)           ;VS=row                    ;VB=v0')
 if(refract)   call gesdict (n, nk, dct_trdmin,   'VN=dct_trdmin   ;ON=DC3I;VD=level of the third local min (IR/RF)           ;VS=row                    ;VB=v0')
               call gesdict (n, nk, dhdx,         'VN=dhdx         ;ON=Y7  ;VD=unresolved topo corr tensor(X)                 ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, dhdxdy,       'VN=dhdxdy       ;ON=Y9  ;VD=unresolv topo corr tensor(XY)                  ;VS=row                    ;VB=p0')
               call gesdict (n, nk, dhdxdyen,     'VN=dhdxdyen     ;ON=OW  ;VD=unresolved topo corr tensor(XY) (E)            ;VS=row                    ;VB=e1;IN=Y9')
               call gesdict (n, nk, dhdxen,       'VN=dhdxen       ;ON=OX  ;VD=unresolved topo corr tensor(X)(E)              ;VS=row                    ;VB=e1;IN=Y7  ;MIN=0')
               call gesdict (n, nk, dhdy,         'VN=dhdy         ;ON=Y8  ;VD=unresolved topo corr tensor(Y)                 ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, dhdyen,       'VN=dhdyen       ;ON=OY  ;VD=unresolved topo corr tensor(Y)(E)              ;VS=row                    ;VB=e1;IN=Y8  ;MIN=0')
               call gesdict (n, nk, dlat,         'VN=dlat         ;ON=LA  ;VD=latitude                                       ;VS=row                    ;VB=p0')
               call gesdict (n, nk, dlon,         'VN=dlon         ;ON=LO  ;VD=longitude                                      ;VS=row                    ;VB=p0')
 if(lcn_my2)   call gesdict (n, nk, dm_c,         'VN=dm_c         ;ON=DMC ;VD=mean-mass diameter of cloud                    ;VS=slc                    ;VB=v0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, dm_g,         'VN=dm_g         ;ON=DMG ;VD=mean-mass diameter of graupel                  ;VS=slc                    ;VB=v0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, dm_h,         'VN=dm_h         ;ON=DMH ;VD=mean-mass diameter of hail                     ;VS=slc                    ;VB=v0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, dm_i,         'VN=dm_i         ;ON=DMI ;VD=mean-mass diameter of ice                      ;VS=slc                    ;VB=v0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, dm_r,         'VN=dm_r         ;ON=DMR ;VD=mean-mass diameter of rain                     ;VS=slc                    ;VB=v0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, dm_s,         'VN=dm_s         ;ON=DMS ;VD=mean-mass diameter of snow                     ;VS=slc                    ;VB=v0        ;MIN=0')
 if(lkfbe)     call gesdict (n, nk, dmfkfc,       'VN=dmfkfc       ;ON=U5  ;VD=downward mass flux in KF                       ;VS=slc                    ;VB=p0')
 if(lmoyhrkf)  call gesdict (n, nk, dmfkfcm,      'VN=dmfkfcm      ;ON=5K  ;VD=avg dmfkfc                                     ;VS=slc                    ;VB=p0')
               call gesdict (n, nk, dxdy,         'VN=dxdy         ;ON=DX  ;VD=area of each model grid tile                   ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, ecc,          'VN=ecc          ;ON=ecc ;VD=2-D total effective cloud cover(cccmarad)      ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, ecch,         'VN=ecch         ;ON=ecch;VD=2-D effective high cloud cover(cccmarad)       ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, eccl,         'VN=eccl         ;ON=eccl;VD=2-D effective low cloud cover(cccmarad)        ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, eccm,         'VN=eccm         ;ON=eccm;VD=2-D effective mid cloud cover(cccmarad)        ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, ei,           'VN=ei           ;ON=EI  ;VD=outgoing IR energy flux at model lid           ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, eiaf,         'VN=eiaf         ;ON=AR  ;VD=accumulation of ei                             ;VS=row                    ;VB=p0        ;MIN=0')
 if(nadvtke)   call gesdict (n, nk, en,           'VN=en           ;ON=EN  ;VD=turbulent kinetic energy                       ;VS=sls                    ;VB=p0        ;MIN=0')
 if(ladvtke)   call gesdict (n, nk, enmoins,      'VN=enmoins      ;ON=EM  ;VD=turbulent kinetic energy at time -             ;VS=sls                    ;VB=d1        ;MIN=0')
               call gesdict (n, nk, epstfn,       'VN=epstfn       ;ON=EP  ;VD=Stephan-Boltzman constant                      ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, esdiag,       'VN=esdiag       ;ON=ED  ;VD=screen level dewpoint depression               ;VS=row                    ;VB=v0')
               call gesdict (n, nk, ev,           'VN=ev           ;ON=EV  ;VD=outgoing VIS energy flux at model lid          ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, ev0,          'VN=ev0          ;ON=E0  ;VD=ev at mid time interval                        ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, evaf,         'VN=evaf         ;ON=AU  ;VD=accumulation of ev                             ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, f12,          'VN=f12          ;ON=12  ;VD=cloud to rain coll tend (condensation)         ;VS=slc                    ;VB=v0')
               call gesdict (n, nk, fadb,         'VN=fadb         ;ON=fadb;VD=direct flux in SW sub-bands                    ;VS=row*6                  ;VB=v0        ;MIN=0')
               call gesdict (n, nk, fafb,         'VN=fafb         ;ON=fafb;VD=diffuse flux in SW sub-bands                   ;VS=row*6                  ;VB=v0        ;MIN=0')
               call gesdict (n, nk, fatb,         'VN=fatb         ;ON=fatb;VD=flux in SW sub-bands                           ;VS=row*6                  ;VB=v0        ;MIN=0')
               call gesdict (n, nk, fbl,          'VN=fbl          ;ON=NC  ;VD=boundary layer cloud fraction                  ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, fc,           'VN=fc           ;ON=FC  ;VD=surface sensible heat flux                     ;VS=row*'//nagg//'@'//nm//';VB=v0')
               call gesdict (n, nk, fcaf,         'VN=fcaf         ;ON=AH  ;VD=accumulation of fc                             ;VS=row                    ;VB=p0')
               call gesdict (n, nk, fcdb,         'VN=fcdb         ;ON=fcdb;VD=clear sky direct flux in SW sub-bands          ;VS=row*6                  ;VB=v0        ;MIN=0')
               call gesdict (n, nk, fcfb,         'VN=fcfb         ;ON=fcfb;VD=clear sky diffuse flux in SW sub-bands         ;VS=row*6                  ;VB=v0        ;MIN=0')
 if(lmoyhr)    call gesdict (n, nk, fcmy,         'VN=fcmy         ;ON=AY  ;VD=FC average over last moyhr hours               ;VS=row                    ;VB=p0')
               call gesdict (n, nk, fcor,         'VN=fcor         ;ON=WC  ;VD=Coriolos factor                                ;VS=row                    ;VB=v0')
               call gesdict (n, nk, fcpflg,       'VN=fcpflg       ;ON=FF  ;VD=Fritsch-Chappell scheme flag                   ;VS=row                    ;VB=p0')
               call gesdict (n, nk, fctb,         'VN=fctb         ;ON=fctb;VD=clear sky flux in SW sub-bands                 ;VS=row*6                  ;VB=v0        ;MIN=0')
               call gesdict (n, nk, fdc,          'VN=fdc          ;ON=CK  ;VD=deep convective clouds                         ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, fdsi,         'VN=fdsi         ;ON=FI  ;VD=IR energy flux towards ground                  ;VS=row                    ;VB=p0        ;MIN=0')
 if(offline)   call gesdict (n, nk, tmp,          'VN=fdsien       ;ON=FIEN;VD=IR energy flux towards ground (offline)        ;VS=row                    ;VB=e1;IN=FI  ;MIN=0')
               call gesdict (n, nk, fdss,         'VN=fdss         ;ON=FS  ;VD=VIS flux absorbed by ground                    ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, fdss0,        'VN=fdss0        ;ON=F0  ;VD=fdss at mid time interval                      ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, fevp,         'VN=fevp         ;ON=pv  ;VD= evap. of strat. precip (condensation)         ;VS=slc                    ;VB=v0')
               call gesdict (n, nk, fiaf,         'VN=fiaf         ;ON=AD  ;VD=accumulation of fdsi                           ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, fice,         'VN=fice         ;ON=F8  ;VD=ice fraction from condens.                     ;VS=slc                    ;VB=p0        ;MIN=0')
 if(lbourg)    call gesdict (n, nk, fip,          'VN=fip          ;ON=P5  ;VD=% of liq. precip. rate IP                      ;VS=row                    ;VB=v0        ;MIN=0')
 if(lbourg3d)  call gesdict (n, nk, fip,          'VN=fip          ;ON=FIP ;VD=% of liq. precip. rate IP                      ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, fl,           'VN=fl           ;ON=FL  ;VD=heat flux in the ground                        ;VS=row@'//nm//'           ;VB=v0')
               call gesdict (n, nk, flaf,         'VN=flaf         ;ON=AG  ;VD=accumulation of heat flux in the ground        ;VS=row                    ;VB=p0')
               call gesdict (n, nk, flagmxp,      'VN=flagmxp      ;ON=FG  ;VD=flag for mixphase)                             ;VS=slc                    ;VB=v0')
               call gesdict (n, nk, fluslop,      'VN=fluslop      ;ON=FBSL;VD=VIS flux twrds slp ground                      ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, flusolaf,     'VN=flusolaf     ;ON=N4  ;VD=accum. of solar radation                       ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, flusolis,     'VN=flusolis     ;ON=FB  ;VD=VIS flux towards ground                        ;VS=row                    ;VB=p0        ;MIN=0')
 if(offline)   call gesdict (n, nk, tmp,          'VN=flusolisen   ;ON=FBEN;VD=VIS flux towards ground (offline)              ;VS=row                    ;VB=e1;IN=FB  ;MIN=0')
               call gesdict (n, nk, fluxdl,       'VN=fluxdl       ;ON=FLDL;VD=flux down lw                                   ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, fluxds,       'VN=fluxds       ;ON=flds;VD=flux down sw                                   ;VS=slc                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, fluxds0,      'VN=fluxds0      ;ON=F0DS;VD=flux down sw at mid T                          ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, fluxul,       'VN=fluxul       ;ON=FLUL;VD=flux up lw                                     ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, fluxus,       'VN=fluxus       ;ON=flus;VD=flux up sw                                     ;VS=slc                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, fluxus0,      'VN=fluxus0      ;ON=F0US;VD=flux up sw at mid T                            ;VS=slc                    ;VB=p0        ;MIN=0')
 if(lbourg)    call gesdict (n, nk, fneige,       'VN=fneige       ;ON=WO  ;VD=% of snow rate                                 ;VS=row                    ;VB=v0        ;MIN=0')
 if(lbourg3d)  call gesdict (n, nk, fneige,       'VN=fneige       ;ON=WO  ;VD=% of snow rate                                 ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, fnn,          'VN=fnn          ;ON=FE  ;VD=flux enhancement factor                        ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, fnsi,         'VN=fnsi         ;ON=SI  ;VD=IR energy flux at the surface                  ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, fq,           'VN=fq           ;ON=FQ  ;VD=surf. momentum flux                            ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, fqaf,         'VN=fqaf         ;ON=AW  ;VD=accumulation of fq                             ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, frv,          'VN=frv          ;ON=B5  ;VD=friction velocity                              ;VS=row*'//nagg//'@'//nm//';VB=p0        ;MIN=0')
 if(lrslp)     call gesdict (n, nk, fsa,          'VN=fsa          ;ON=FSA ;VD=fraction of aspect                             ;VS=row*4                  ;VB=e1;IN=FSA ;')
               call gesdict (n, nk, fsaf,         'VN=fsaf         ;ON=AS  ;VD=accumulation of fdss                           ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, fsamoon,      'VN=fsamoon      ;ON=FSAM;VD=energy absbd btn toa and mdl top               ;VS=row                    ;VB=p0')
 if(lshal)     call gesdict (n, nk, fsc,          'VN=fsc          ;ON=FSC ;VD=shallow convection clouds                      ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, fsd,          'VN=fsd          ;ON=FSD ;VD=direct sw downward flx at sfc                  ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, fsd0,         'VN=fsd0         ;ON=FSD0;VD=direct sw downward flx at sfc at mid T         ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, fsdaf,        'VN=fsdaf        ;ON=AFSD;VD=accumulation of fsd                            ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, fsf,          'VN=fsf          ;ON=FSF ;VD=diffuse sw downward flx at sfc                 ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, fsf0,         'VN=fsf0         ;ON=FSF0;VD=diffuse sw downward flx at sfc at mid T        ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, fsfaf,        'VN=fsfaf        ;ON=AFSF;VD=accumulation of fsf                            ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, fsg,          'VN=fsg          ;ON=FSG ;VD=downward flx absorbd by sfc                    ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, fsi,          'VN=fsi          ;ON=FSI ;VD=near IR downward flx at sfc                    ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, fsi0,         'VN=fsi0         ;ON=FSI0;VD=near IR downward flx at sfc at mid T           ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, fsiaf,        'VN=fsiaf        ;ON=AFSI;VD=accumulation of fsi                            ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, fsv,          'VN=fsv          ;ON=FSV ;VD=vis downward flx at sfc                        ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, fsv0,         'VN=fsv0         ;ON=FSV0;VD=vis downward flx at sfc at mid T               ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, fsvaf,        'VN=fsvaf        ;ON=AFSV;VD=accumulation of fsv                            ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, ftemp,        'VN=ftemp        ;ON=FT  ;VD=sfc. temperature flux (T-DT)                   ;VS=row*'//nagg//'@'//nm//';VB=p0')
               call gesdict (n, nk, ftot,         'VN=ftot         ;ON=FN  ;VD=total clouds                                   ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, fv,           'VN=fv           ;ON=FV  ;VD=surface latent flux                            ;VS=row*'//nagg//'@'//nm//';VB=v0')
               call gesdict (n, nk, fvaf,         'VN=fvaf         ;ON=AV  ;VD=accumulation of fv                             ;VS=row                    ;VB=p0')
               call gesdict (n, nk, fvap,         'VN=fvap         ;ON=HF  ;VD=surf. vapour flux (T-DT)                       ;VS=row*'//nagg//'@'//nm//';VB=p0')
 if(lmoyhr)    call gesdict (n, nk, fvmy,         'VN=fvmy         ;ON=AZ  ;VD=FV average over last moyhr hours               ;VS=row                    ;VB=p0')
               call gesdict (n, nk, fxp,          'VN=fxp          ;ON=NS  ;VD=stratiform clouds                              ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, gc,           'VN=gc           ;ON=GC  ;VD=ground cover (-1,0,1)                          ;VS=row                    ;VB=p0')
               call gesdict (n, nk, glsea,        'VN=glsea        ;ON=GL  ;VD=sea ice fraction                               ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, gq,           'VN=gq           ;ON=GQ  ;VD=countergrad. for Q diffu.                      ;VS=slc                    ;VB=v0')
               call gesdict (n, nk, gql,          'VN=gql          ;ON=G1  ;VD=countergrad. for QL diffu.                     ;VS=slc                    ;VB=v0')
               call gesdict (n, nk, gte,          'VN=gte          ;ON=GT  ;VD=countergrad. for T diffu.                      ;VS=slc                    ;VB=v0')
               call gesdict (n, nk, gz_moins,     'VN=PW_GZ:M      ;ON=GZM ;VD=geopotential at t-dt on momentum levels        ;VS=slb                    ;VB=d1')
               call gesdict (n, nk, gzmom,        'VN=gzmom        ;ON=GZMO;VD=geop. heights on momentum levels               ;VS=sls                    ;VB=v0')
               call gesdict (n, nk, gztherm,      'VN=gztherm      ;ON=GZTH;VD=geop. heights on thermodynamic levels          ;VS=sls                    ;VB=v0')
               call gesdict (n, nk, ze,           'VN=ze           ;ON=2J  ;VD=geop. heights on "energy" levels               ;VS=sls                    ;VB=v0')
               call gesdict (n, nk, h,            'VN=h            ;ON=H   ;VD=height of boundary layer                       ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, h_cb,         'VN=h_cb         ;ON=H_CB;VD=height of cloud base                           ;VS=row                    ;VB=v0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, h_m2,         'VN=h_m2         ;ON=H_M2;VD=height of highest melting level                ;VS=row                    ;VB=v0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, h_ml,         'VN=h_ml         ;ON=H_ML;VD=height of lowest melting level                 ;VS=row                    ;VB=v0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, h_sn,         'VN=h_sn         ;ON=H_SN;VD=height of snow level                           ;VS=row                    ;VB=v0        ;MIN=0')
 if(lmoyhr)    call gesdict (n, nk, hrsmax,       'VN=hrsmax       ;ON=HRMX;VD=screen max rel hum over last moyhr hours       ;VS=row                    ;VB=p0        ;MIN=0')
 if(lmoyhr)    call gesdict (n, nk, hrsmin,       'VN=hrsmin       ;ON=HRMN;VD=screen min rel hum over last moyhr hours       ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, hst,          'VN=hst          ;ON=H1  ;VD=PBL height for stable case                     ;VS=row*'//nagg//'@'//nm//';VB=p0        ;MIN=0')
               call gesdict (n, nk, hucond,       'VN=hucond       ;ON=QA  ;VD=HU tendency due to conv./cond.                 ;VS=slc                    ;VB=v1')
 if(lkfbe)     call gesdict (n, nk, hufcp,        'VN=hufcp        ;ON=H3  ;VD=HU tendency due to FCP                         ;VS=slc                    ;VB=p0')
 if(lmoyhrkf)  call gesdict (n, nk, hufcpm,       'VN=hufcpm       ;ON=2K  ;VD=avg HU tendency kfcp over last moyhr hours     ;VS=slc                    ;VB=p0')
               call gesdict (n, nk, humoins,      'VN=TR/hu:M,min=0;ON=H8  ;VD=specific humidity at t-dt                      ;VS=slc                    ;VB=d1')
               call gesdict (n, nk, huphytd,      'VN=phytd_hu     ;ON=QPHY;VD=total Q tendency due to physics                ;VS=slc                    ;VB=v1')
 if(lmoyhr)    call gesdict (n, nk, huphytdm,     'VN=huphytdm     ;ON=QPHM;VD=total HU physics tdcy avg over the moyhr hrs   ;VS=slc                    ;VB=p0')
               call gesdict (n, nk, huplus,       'VN=TR/hu:P,min=0;ON=UH  ;VD=specific humidity at t+dt                      ;VS=slc                    ;VB=d1;IN=HU')
 if(lmoyhr)    call gesdict (n, nk, husavg,       'VN=husavg       ;ON=QSAV;VD=screen spec hum average over last moyhr hours  ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, hushal,       'VN=hushal       ;ON=SQ  ;VD=HU tendency due to shallow conv.               ;VS=slc                    ;VB=v0')
 if(lmoyhr)    call gesdict (n, nk, hushalm,      'VN=hushalm      ;ON=X7  ;VD=avg HU tendcy shal conv. over last moyhr hrs   ;VS=slc                    ;VB=p0')
               call gesdict (n, nk, icep,         'VN=icep         ;ON=ICEP;VD=ISCCP cloud variability (epilson)              ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, ictp,         'VN=ictp         ;ON=ICTP;VD=ISCCP cloud top pressure                       ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, icw,          'VN=icw          ;ON=IE  ;VD=integrated cloud water/ice                     ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, ilmo,         'VN=ilmo         ;ON=IO  ;VD=(length of Monin-Obukhov)**-1                  ;VS=row*'//nagg//'@'//nm//';VB=p0')
               call gesdict (n, nk, isun,         'VN=isun         ;ON=ISUN;VD=ISCCP sunlit parameter (mu >= 0.2)             ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, itau,         'VN=itau         ;ON=ITAU;VD=ISCCP cloud optical thickness                  ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, itcf,         'VN=itcf         ;ON=ITCF;VD=ISCCP total cloud fraction                     ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, itp,          'VN=itp          ;ON=ITP ;VD=ISCCP cloud top pressure/tau hostograms        ;VS=row*'//nipt//'         ;VB=p0        ;MIN=0')
               call gesdict (n, nk, iv,           'VN=iv           ;ON=IV  ;VD=incoming solar flux at model lid               ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, ivaf,         'VN=ivaf         ;ON=AB  ;VD=accumulation of iv                             ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, iwc,          'VN=iwc          ;ON=QE  ;VD=cloud ice content at time T                    ;VS=slc                    ;VB=p0        ;MIN=0')
 if(lmoyhr)    call gesdict (n, nk, iwcm,         'VN=iwcm         ;ON=Y2  ;VD=cloud ice water content avg over lst moyhr hrs ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, iwcrad,       'VN=iwcrad       ;ON=IWCR;VD=ice w.cont. for radiation                      ;VS=slc                    ;VB=v0        ;MIN=0')
 if(lmoyhr)    call gesdict (n, nk, iwcradm,      'VN=iwcradm      ;ON=IWRM;VD=cloud ice water for rad  avg ovr lst moyhr hrs ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, iwp,          'VN=iwp          ;ON=II  ;VD=integrated ice water                           ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, iwv,          'VN=iwv          ;ON=IH  ;VD=integrated water vapor                         ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, iwv700,       'VN=iwv700       ;ON=IY  ;VD=int. water vapor (0-700 mb)                    ;VS=row                    ;VB=v0        ;MIN=0')
 if(lmoyhr)    call gesdict (n, nk, iwvm,         'VN=iwvm         ;ON=IWVM;VD=int water vapor avge over last moyhr hrs       ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, kcl,          'VN=kcl          ;ON=KC  ;VD=1st level in the PBL                           ;VS=row                    ;VB=v0        ;MIN=0')
 if(lkfbe)     call gesdict (n, nk, kfcrf,        'VN=kfcrf        ;ON=L3  ;VD=liquid precip flux from KF                     ;VS=slc                    ;VB=p0        ;MIN=0')
 if(lkfbe)     call gesdict (n, nk, kfcsf,        'VN=kfcsf        ;ON=L4  ;VD=solid precip  flux from KF                     ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, kkfc,         'VN=kkfc         ;ON=K3  ;VD=counter for kfc                                ;VS=row                    ;VB=v0')
 if(lmoyhrkf)  call gesdict (n, nk, kkfcm,        'VN=kkfcm        ;ON=0K  ;VD=avg kkfc                                       ;VS=row                    ;VB=p0')
               call gesdict (n, nk, km,           'VN=km           ;ON=KM  ;VD=momentum vertical diff. coeff.(m2/s)           ;VS=sls                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, kshal,        'VN=kshal        ;ON=K9  ;VD=counter for ktrsnt                             ;VS=row                    ;VB=v0')
 if(lmoyhr)    call gesdict (n, nk, kshalm,       'VN=kshalm       ;ON=K2  ;VD=avg of kshal counter                           ;VS=row                    ;VB=p0')
               call gesdict (n, nk, kt,           'VN=kt           ;ON=KT  ;VD=T/HU vertical diff. coeff.(m2/s)               ;VS=sls                    ;VB=v0        ;MIN=0')
 if(lmoistke)  call gesdict (n, nk, ldifv,        'VN=ldifv        ;ON=LDIF;VD=cloud water content tendency due to vert.diff. ;VS=slc                    ;VB=v1')
               call gesdict (n, nk, lhtg,         'VN=lhtg         ;ON=LH  ;VD=unresolved orography variance                  ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, lhtgen,       'VN=lhtgen       ;ON=LE  ;VD=unresolved orography variance2                 ;VS=row                    ;VB=e1;IN=LH  ;MIN=0')
               call gesdict (n, nk, lwc,          'VN=lwc          ;ON=QD  ;VD=cloud/water content at time T                  ;VS=slc                    ;VB=p0        ;MIN=0')
 if(lmoyhr)    call gesdict (n, nk, lwcm,         'VN=lwcm         ;ON=Y1  ;VD=cloud liq water cont avg ovr lst moyhr hours   ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, lwcrad,       'VN=lwcrad       ;ON=LWCR;VD=liquid wc for radiation                        ;VS=slc                    ;VB=v0        ;MIN=0')
 if(lmoyhr)    call gesdict (n, nk, lwcradm,      'VN=lwcradm      ;ON=LWRM;VD=liquid wc for rad avg over last moyhr hours    ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, lwp2,         'VN=lwp2         ;ON=IC  ;VD=liquid water path (Sundqvist)                  ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, mg,           'VN=mg           ;ON=MG  ;VD=land-sea mask                                  ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, ml,           'VN=ml           ;ON=ML  ;VD=fraction of lakes (mask)                       ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, mol,          'VN=mol          ;ON=OL  ;VD=Monin-Obukhov length [-1000,1000]              ;VS=row                    ;VB=v0')
 if(stochphy)  call gesdict (n, nk, mrk2,         'VN=mrk2         ;ON=BB  ;VD=Markov field 2d                                ;VS=row*'//nmar//'         ;VB=p0')
 if(stochphy)  call gesdict (n, nk, mrkv,         'VN=mrkv         ;ON=AA  ;VD=Markov field 3d                                ;VS=slb                    ;VB=p0')
               call gesdict (n, nk, mtdir,        'VN=mtdir        ;ON=Y6  ;VD=unresolved topo direction                      ;VS=row                    ;VB=p0')
               call gesdict (n, nk, nbas,         'VN=nbas         ;ON=NB  ;VD=low cloud amount                               ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, nhaut,        'VN=nhaut        ;ON=NH  ;VD=high cloud amount                              ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, nmoy,         'VN=nmoy         ;ON=NM  ;VD=middle cloud amount                            ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, nt,           'VN=nt           ;ON=NT  ;VD=2-D total effective cloud cover(newrad style)  ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, ntaf,         'VN=ntaf         ;ON=NF  ;VD=accumulation of nt                             ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, o3s,          'VN=o3s          ;ON=O3S ;VD=ozone                                          ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, oztoit,       'VN=oztoit       ;ON=OZTO;VD=avg mixing ratio o3 abv roof                   ;VS=row                    ;VB=p0        ;MIN=0')
 if(lmoyhr)    call gesdict (n, nk, p0avg,        'VN=p0avg        ;ON=P0AV;VD=surface pressure average over last moyhr hours ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, parr,         'VN=parr         ;ON=PARR;VD=photosynthetic active radiation                ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, parr0,        'VN=parr0        ;ON=PAR0;VD=photosynthetic active radiation at mid T       ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, parraf,       'VN=parraf       ;ON=APAR;VD=accumulation of par                            ;VS=row                    ;VB=p0        ;MIN=0')
 if(lpblcpl)   call gesdict (n, pbl_nk+1, pbl_gq, 'VN=pbl_gq       ;ON=BLGQ;VD=countergrad. for Q diffu. on PBL levels        ;VS=slb                    ;VB=v0')
 if(lpblcpl)   call gesdict (n, pbl_nk+1, pbl_gql, 'VN=pbl_gql     ;ON=BLG1;VD=countergrad. for QL diffu. on PBL levels       ;VS=slb                    ;VB=v0')
 if(lpblcpl)   call gesdict (n, pbl_nk+1, pbl_gte, 'VN=pbl_gte     ;ON=BLGT;VD=countergrad. for T diffu. on PBL levels        ;VS=slb                    ;VB=v0')
 if(lpblcpl)   call gesdict (n, pbl_nk+1, pbl_humoins, 'VN=pbl_humoins;ON=BLCE;VD=humidity on PBL levels at time minus        ;VS=sls                    ;VB=p0        ;MIN=0')
 if(lpblcpl)   call gesdict (n, pbl_nk+1, pbl_km, 'VN=pbl_km       ;ON=BLKM;VD=mom. vert. diff. coeff. on PBL levels(m2/s)    ;VS=sls                    ;VB=v0        ;MIN=0')
 if(lpblcpl)   call gesdict (n, pbl_nk+1, pbl_kt, 'VN=pbl_kt       ;ON=BLKT;VD=therm. vert. diff. coeff. on PBL levels(m2/s)  ;VS=sls                    ;VB=v0        ;MIN=0')
 if(lpblcpl)   call gesdict (n, pbl_nk+1, pbl_qcmoins, 'VN=pbl_qcmoins;ON=BLQC;VD=QC on PBL levels at time minus              ;VS=sls                    ;VB=p0        ;MIN=0')
 if(lpblcpl)   call gesdict (n, pbl_nk+1, pbl_qtbl, 'VN=pbl_qtbl   ;ON=BLQT;VD=implicit cloud on PBL energy levels            ;VS=slb                    ;VB=p0        ;MIN=0')
 if(lpblcpl)   call gesdict (n, pbl_nk+1, pbl_tke, 'VN=pbl_tke     ;ON=BLKE;VD=turbulent kinetic energy on PBL levels         ;VS=sls                    ;VB=p0        ;MIN=0')
 if(lpblcpl)   call gesdict (n, pbl_nk+1, pbl_tmoins, 'VN=pbl_tmoins;ON=BLTE;VD=temperature on PBL levels at time minus       ;VS=slb                    ;VB=p0')
 if(lpblcpl)   call gesdict (n, pbl_nk+1, pbl_turbreg, 'VN=pbl_turbreg;ON=BLTB;VD=turbulence regime for coupled PBL scheme    ;VS=sls                    ;VB=p0')
 if(lpblcpl)   call gesdict (n, pbl_nk+1, pbl_umoins, 'VN=pbl_umoins;ON=BLUM;VD=u-wind on PBL momentum levels at time minus   ;VS=slb                    ;VB=p0')
 if(lpblcpl)   call gesdict (n, pbl_nk+1, pbl_vmoins, 'VN=pbl_vmoins;ON=BLVM;VD=v-wind on PBL momentum levels at time minus   ;VS=slb                    ;VB=p0')
 if(lpblcpl)   call gesdict (n, pbl_nk+1, pbl_zn, 'VN=pbl_zn       ;ON=BLZN;VD=mixing length of turbulence on PBL levels      ;VS=sls                    ;VB=p0        ;MIN=0')
 if(lpblcpl)   call gesdict (n, nk, pblm_humoins, 'VN=pblm_humoins ;ON=BMH ;VD=humidity at previous PBL call                  ;VS=slb                    ;VB=p0        ;MIN=0')
 if(lpblcpl)   call gesdict (n, nk, pblm_qcmoins, 'VN=pblm_qcmoins ;ON=BMCE;VD=QC at previous PBL call                        ;VS=sls                    ;VB=p0        ;MIN=0')
 if(lpblcpl)   call gesdict (n, nk, pblm_tmoins, 'VN=pblm_tmoins   ;ON=BMT ;VD=temperature at previous PBL call               ;VS=slb                    ;VB=p0')
 if(lpblcpl)   call gesdict (n, nk, pblm_umoins, 'VN=pblm_umoins   ;ON=BMU ;VD=u-wind at previous PBL call                    ;VS=slb                    ;VB=p0')
 if(lpblcpl)   call gesdict (n, nk, pblm_vmoins, 'VN=pblm_vmoins   ;ON=BMV ;VD=v-wind at previous PBL call                    ;VS=slb                    ;VB=p0')
               call gesdict (n, nk, pc,           'VN=pc           ;ON=PC  ;VD=accum. of implicit precip.                     ;VS=row                    ;VB=v0        ;MIN=0')
 if(lkfbe)     call gesdict (n, nk, peffkfc,      'VN=peffkfc      ;ON=U7  ;VD=precipitation efficiency in KF                 ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, phit0,        'VN=phit0        ;ON=X0  ;VD=stability function value(z=0)                  ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, pmoins,       'VN=pmoins       ;ON=P8  ;VD=surface pressure at t-dt                       ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, pr,           'VN=pr           ;ON=PR  ;VD=accum. of total precip.                        ;VS=row                    ;VB=v0        ;MIN=0')
 if(lkfbe)    call gesdict (n, nk, prcten,       'VN=prcten       ;ON=TQCD;VD=Deep Conv qc tendency (1/s)                     ;VS=slb                    ;VB=p0')
 if(lkfbe)    call gesdict (n, nk, priten,       'VN=priten       ;ON=TQID;VD=Deep Conv qi tendency (1/s)                     ;VS=slb                    ;VB=p0')
 if(offline)   call gesdict (n, nk, tmp,          'VN=pren         ;ON=PREN;VD=1h accum. of total precip. (offline)           ;VS=row                    ;VB=e1;IN=PR0 ;MIN=0')
               call gesdict (n, nk, py,           'VN=py           ;ON=PY  ;VD=accum. of deep conv. precip.                   ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, pz,           'VN=pz           ;ON=PZ  ;VD=accum. of shal. conv. precip.                  ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, qadv,         'VN=qadv         ;ON=QADV;VD=Q advection tendency                           ;VS=slc                    ;VB=v1')
 if(lmoyhr)    call gesdict (n, nk, qadvm,        'VN=qadvm        ;ON=QADM;VD=Q adv tend. avge over last moyhr hrs           ;VS=slc                    ;VB=p0')
 if(lkfbe)     call gesdict (n, nk, qckfc,        'VN=qckfc        ;ON=Q7  ;VD=cloud water/ice tend. due to KFC               ;VS=slc                    ;VB=p0')
 if(lmoyhrkf)  call gesdict (n, nk, qckfcm,       'VN=qckfcm       ;ON=3K  ;VD=avg qc tendency kfcp                           ;VS=slc                    ;VB=p0')
 if(.not.lcn_mpx)  call gesdict (n, nk, qcmoins,  'VN=TR/qc:M,wload=1,min=0 ;ON=Q9  ;VD=total condensate mixing ratio at t-dT ;VS=slc                    ;VB=d'//need_wz)
 if(.not.lcn_mpx)  call gesdict (n, nk, qcphytd,  'VN=phytd_qc     ;ON=QT  ;VD=QC tendency due to conv./cond.                 ;VS=slc                    ;VB=v1')
 if(.not.lcn_mpx)  call gesdict (n, nk, qcplus,   'VN=TR/qc:P,wload=1,min=0 ;ON=CQ  ;VD=total condensate mixing ratio at t+dT          ;VS=slc                 ;VB=d'//need_wz//';IN=QC')
               call gesdict (n, nk, qcz,          'VN=qcz          ;ON=QZ  ;VD=Cloud water Detrained by ktrsnt                ;VS=slc                    ;VB=v0')
               call gesdict (n, nk, qdiag,        'VN=qdiag        ;ON=DQ  ;VD=screen level specific humidity                 ;VS=row@'//nm//'           ;VB=p0        ;MIN=0')
               call gesdict (n, nk, qdifv,        'VN=qdifv        ;ON=Q8  ;VD=Q tendency due to vert. diffusion              ;VS=slc                    ;VB=v1')
 if(lmoyhr)    call gesdict (n, nk, qdifvm,       'VN=qdifvm       ;ON=X4  ;VD=HU dif. tend. avge over last moyhr hrs         ;VS=slc                    ;VB=p0')
 if(lkfbe)     call gesdict (n, nk, qldi,         'VN=qldi         ;ON=QLDI;VD=liquid mixing ratio in KF                      ;VS=slc                    ;VB=p0        ;MIN=0')
 if(lshal)     call gesdict (n, nk, qlsc,         'VN=qlsc         ;ON=QLSC;VD=liq. cloud water content for ktrsnt            ;VS=slc                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, qmetox,       'VN=qmetox       ;ON=QX  ;VD=Hum. tend. due to methane oxidation            ;VS=slc                    ;VB=v1')
 if(lmoyhr)    call gesdict (n, nk, qmetoxm,      'VN=qmetoxm      ;ON=QXM ;VD=QX average over last moyhr hour                ;VS=slc                    ;VB=p0')
 if(lkfbe)     call gesdict (n, nk, qrkfc,        'VN=qrkfc        ;ON=S3  ;VD=rain  water/snow tend. due to KFC              ;VS=slc                    ;VB=p0')

 if(.not.lcn_mpx)  call gesdict (n, nk, qrphytd,  'VN=rain_td      ;ON=Q5  ;VD=QL tendency due to conv./cond.                 ;VS=slc                    ;VB=v0')
 if(lkfbe)     call gesdict (n, nk, qsdi,         'VN=qsdi         ;ON=QSDI;VD=ice mixing ratio in KF                         ;VS=slc                    ;VB=p0        ;MIN=0')
 if(lshal)     call gesdict (n, nk, qssc,         'VN=qssc         ;ON=QSSC;VD=sol. cloud water content for ktrsnt            ;VS=slc                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, qsurf,        'VN=qsurf        ;ON=J9  ;VD=area-averaged surf. spec. humidity             ;VS=row*'//nagg//'@'//nm//';VB=p0        ;MIN=0')
               call gesdict (n, nk, qtbl,         'VN=qtbl         ;ON=QTBL;VD=bound. layer sgs cloud wc                      ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, qtde,         'VN=qtde         ;ON=QTDE;VD=total deep convection detrained condensate     ;VS=slc                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, rainaf,       'VN=rainaf       ;ON=RNAC;VD=accum. of liquid precip.(ISBA)                 ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, rainrate,     'VN=rainrate     ;ON=U1  ;VD=liquid precip. rate                            ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, rc,           'VN=rc           ;ON=RC  ;VD=implicit precip. rate                          ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, rckfc,        'VN=rckfc        ;ON=KF  ;VD=KFC/FCP convective precip. rate                ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, rhdiag,       'VN=rhdiag       ;ON=RH  ;VD=screen level relative humidity                 ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, rib,          'VN=rib          ;ON=RB  ;VD=Bulk Richardson number [-10,5]                 ;VS=row@'//nm//'           ;VB=v0')
               call gesdict (n, nk, rif,          'VN=rif          ;ON=RIF ;VD=Flux Richardson number                         ;VS=sls                    ;VB=v0')
               call gesdict (n, nk, rig,          'VN=rig          ;ON=RIG ;VD=Gradient Richardson number                     ;VS=sls                    ;VB=v0')
 if(lkfbe)     call gesdict (n, nk, rice_int,     'VN=rice_int     ;ON=L7  ;VD=vertical integral of rliqout                   ;VS=row                    ;VB=p0        ;MIN=0')
 if(lkfbe)     call gesdict (n, nk, rliq_int,     'VN=rliq_int     ;ON=L8  ;VD=vertical integral of riceout                   ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, rn,           'VN=rn           ;ON=RN  ;VD=accum. of liquid precip.                       ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, rnflx,        'VN=rnflx        ;ON=RF  ;VD=liquid precipitation flux (condensation)       ;VS=slc                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, rr,           'VN=rr           ;ON=RR  ;VD=stratiform precip. rate                        ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, rt,           'VN=rt           ;ON=RT  ;VD=total precipitation rate                       ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, ry,           'VN=ry           ;ON=RY  ;VD=deep convective precip. rate                   ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, rz,           'VN=rz           ;ON=RZ  ;VD=shall. convective precip. rate                 ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, salb6z,       'VN=salb6z       ;ON=SALB;VD=albedo (solar)                                 ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, scl,          'VN=scl          ;ON=SB  ;VD=height of boundary layer in sigma              ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, sdtswd,       'VN=sdtswd       ;ON=SDWD;VD=std dev turb surf wind dir                     ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, sdtsws,       'VN=sdtsws       ;ON=SDWS;VD=std dev turb surf wind speed                   ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, shear2,       'VN=shear2       ;ON=SHR2;VD=square of vertical shear of the horizontal wind;VS=sls                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, siaf,         'VN=siaf         ;ON=AI  ;VD=accumulation of fnsi                           ;VS=row                    ;VB=p0')
               call gesdict (n, nk, sigm,         'VN=PW_PM:P      ;ON=SL  ;VD=sigma momentum values                          ;VS=slb                    ;VB=d1        ;MIN=0')
               call gesdict (n, nk, sigt,         'VN=PW_PT:P      ;ON=SIGT;VD=sigma thermo values                            ;VS=slc                    ;VB=d1        ;MIN=0')
 if(lrslp)     call gesdict (n, nk, sla,          'VN=sla          ;ON=SLA ;VD=mean slope with aspect                         ;VS=row*4                  ;VB=e1;=IN=SLA ;')
               call gesdict (n, nk, slope,        'VN=slope        ;ON=Y4  ;VD=unresolved topo slope                          ;VS=row                    ;VB=p0')
 if(lcn_my2)   call gesdict (n, nk, slw,          'VN=slw          ;ON=SLW ;VD=SLW from microphysics [kg/m^3]                 ;VS=slc                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, slwp,         'VN=slwp         ;ON=IB  ;VD=integrated SLW                                 ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, slwp2,        'VN=slwp2        ;ON=B2  ;VD=integrated SLW (bottom to s2)                  ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, slwp3,        'VN=slwp3        ;ON=B3  ;VD=integrated SLW (s2 to s3)                      ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, slwp4,        'VN=slwp4        ;ON=B4  ;VD=integrated SLW (s3 to s4)                      ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, sn,           'VN=sn           ;ON=SN  ;VD=accum. of snow precip.                         ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, snoflx,       'VN=snoflx       ;ON=SF  ;VD=solid precipitation flux (condensation)        ;VS=slc                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, snowaf,       'VN=snowaf       ;ON=N3  ;VD=accum. of solid precip.                        ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, snowrate,     'VN=snowrate     ;ON=U3  ;VD=solid precip. rate                             ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, sqe,          'VN=sqe          ;ON=SQE ;VD=cond. Q tendency                               ;VS=slc                    ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, ss01,         'VN=ss01         ;ON=SS01;  VD=S/S term 01 from microphysics                  ;VS=slc                    ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, ss02,         'VN=ss02         ;ON=SS02;  VD=S/S term 02 from microphysics                  ;VS=slc                    ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, ss03,         'VN=ss03         ;ON=SS03;  VD=S/S term 03 from microphysics                  ;VS=slc                    ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, ss04,         'VN=ss04         ;ON=SS04;  VD=S/S term 04 from microphysics                  ;VS=slc                    ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, ss05,         'VN=ss05         ;ON=SS05;  VD=S/S term 05 from microphysics                  ;VS=slc                    ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, ss06,         'VN=ss06         ;ON=SS06;  VD=S/S term 06 from microphysics                  ;VS=slc                    ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, ss07,         'VN=ss07         ;ON=SS07;  VD=S/S term 07 from microphysics                  ;VS=slc                    ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, ss08,         'VN=ss08         ;ON=SS08;  VD=S/S term 08 from microphysics                  ;VS=slc                    ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, ss09,         'VN=ss09         ;ON=SS09;  VD=S/S term 09 from microphysics                  ;VS=slc                    ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, ss10,         'VN=ss10         ;ON=SS10;  VD=S/S term 10 from microphysics                  ;VS=slc                    ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, ss11,         'VN=ss11         ;ON=SS11;  VD=S/S term 11 from microphysics                  ;VS=slc                    ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, ss12,         'VN=ss12         ;ON=SS12;  VD=S/S term 12 from microphysics                  ;VS=slc                    ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, ss13,         'VN=ss13         ;ON=SS13;  VD=S/S term 13 from microphysics                  ;VS=slc                    ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, ss14,         'VN=ss14         ;ON=SS14;  VD=S/S term 14 from microphysics                  ;VS=slc                    ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, ss15,         'VN=ss15         ;ON=SS15;  VD=S/S term 15 from microphysics                  ;VS=slc                    ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, ss16,         'VN=ss16         ;ON=SS16;  VD=S/S term 16 from microphysics                  ;VS=slc                    ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, ss17,         'VN=ss17         ;ON=SS17;  VD=S/S term 17 from microphysics                  ;VS=slc                    ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, ss18,         'VN=ss18         ;ON=SS18;  VD=S/S term 18 from microphysics                  ;VS=slc                    ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, ss19,         'VN=ss19         ;ON=SS19;  VD=S/S term 19 from microphysics                  ;VS=slc                    ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, ss20,         'VN=ss20         ;ON=SS20;  VD=S/S term 20 from microphysics                  ;VS=slc                    ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, effradc,      'VN=effradc      ;ON=REFC;  VD=effective radius of drops from microphysics    ;VS=slc                    ;VB=p0        ;MIN=0')
 if(lcn_mpx)  call gesdict (n, nk, effradi,      'VN=effradi      ;ON=REFI;  VD=effective radius of ice from microphysics      ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, ste,          'VN=ste          ;ON=STE ;VD=cond. T tendency                               ;VS=slc                    ;VB=v0')
                call gesdict (n, nk, suaf,         'VN=suaf         ;ON=S7  ;VD=accumulation of ustress                        ;VS=row                    ;VB=p0')
               call gesdict (n, nk, svaf,         'VN=svaf         ;ON=S8  ;VD=accumulation of vstress                        ;VS=row                    ;VB=p0')
               call gesdict (n, nk, t2,           'VN=t2           ;ON=T2  ;VD=VIS heating rate interpo. from T20             ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, t20,          'VN=t20          ;ON=T0  ;VD=VIS heating rate at mid time interval          ;VS=slc                    ;VB=p0        ;MIN=0')
 if(lmoyhr)    call gesdict (n, nk, t2m,          'VN=t2m          ;ON=T6  ;VD=T2 average over last moyhr hours               ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, tadv,         'VN=tadv         ;ON=TADV;VD=T advection tendency                           ;VS=slc                    ;VB=v1')
 if(lmoyhr)    call gesdict (n, nk, tadvm,        'VN=tadvm        ;ON=TADM;VD=T adv tend. avge over last moyhr hrs           ;VS=slc                    ;VB=p0')
 if(lmoyhr)    call gesdict (n, nk, tadvmin,      'VN=tadvmin      ;ON=TAMN;VD=minimum T adv tend. over last moyhr hrs        ;VS=slc                    ;VB=p0')
 if(lmoyhr)    call gesdict (n, nk, tadvmax,      'VN=tadvmax      ;ON=TAMX;VD=maximum T adv tend. over last moyhr hrs        ;VS=slc                    ;VB=p0')
               call gesdict (n, nk, tcc,          'VN=tcc          ;ON=TCC ;VD=2-D total true cloud cover(cccmarad)           ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, tcond,        'VN=tcond        ;ON=TA  ;VD=T tendency due to conv./cond.                  ;VS=slc                    ;VB=v1')
               call gesdict (n, nk, tdew,         'VN=tdew         ;ON=TDK ;VD=dew point temperature at diagnostic level      ;VS=row                    ;VB=v0')
               call gesdict (n, nk, tdiag,        'VN=tdiag        ;ON=TJ  ;VD=screen level temperature                       ;VS=row@'//nm//'           ;VB=p0')
               call gesdict (n, nk, tdiagavg,     'VN=tdiagavg     ;ON=TSAV;VD=screen level temperature average               ;VS=row                    ;VB=p0')
               call gesdict (n, nk, tdifv,        'VN=tdifv        ;ON=TF  ;VD=T tendency due to vert. diffusion              ;VS=slc                    ;VB=v1')
 if(lmoyhr)    call gesdict (n, nk, tdifvm,       'VN=tdifvm       ;ON=X5  ;VD=T dif. tend. avge over last moyhr hrs          ;VS=slc                    ;VB=p0')
 if(lkfbe)     call gesdict (n, nk, tfcp,         'VN=tfcp         ;ON=T4  ;VD=T tendency due to FCP                          ;VS=slc                    ;VB=p0')
 if(lmoyhrkf)  call gesdict (n, nk, tfcpm,        'VN=tfcpm        ;ON=1K  ;VD=avg T tendency kfcp over last moyhr hours      ;VS=slc                    ;VB=p0')
               call gesdict (n, nk, tgno,         'VN=tgno         ;ON=TW  ;VD=T tend. due to non-oro. gwd                    ;VS=slc                    ;VB=v1')
 if(lmoyhr)    call gesdict (n, nk, tgnom,        'VN=tgnom        ;ON=NOTM;VD=NOGW T tend. average over last moyhr hrs       ;VS=slc                    ;VB=p0')
               call gesdict (n, nk, thetaa,       'VN=thetaa       ;ON=N1  ;VD=first-level pot. temp.                         ;VS=row                    ;VB=v0')
               call gesdict (n, nk, ti,           'VN=ti           ;ON=TI  ;VD=IR heating rate                                ;VS=slc                    ;VB=p0')
 if(lmoyhr)    call gesdict (n, nk, tim,          'VN=tim          ;ON=T7  ;VD=TI average over last moyhr hours               ;VS=slc                    ;VB=p0')
               call gesdict (n, nk, tiwp,         'VN=tiwp         ;ON=IIR ;VD=total ice water path for radiation             ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, tiwpin,       'VN=tiwpin       ;ON=W2  ;VD=total in-cloud ice water path (Rockel)         ;VS=row                    ;VB=p0        ;MIN=0')
 if(lmoyhr)    call gesdict (n, nk, tiwpm,        'VN=tiwpm        ;ON=IIRM;VD=total IWP for rad avge over last moyhr hrs     ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, tlc,          'VN=tlc          ;ON=P1  ;VD=liquid convect. precip. rate                   ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, tlcs,         'VN=tlcs         ;ON=A5  ;VD=liquid shall. convect. precip. rate            ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, tls,          'VN=tls          ;ON=P2  ;VD=rain precip. rate, grid-scale cond.            ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, tls_fr1,      'VN=tls_fr1      ;ON=RFR1;VD=pcp rate - freezing drizzle (M-Y)              ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, tls_fr2,      'VN=tls_fr2      ;ON=RFR2;VD=pcp rate - freezing rain    (M-Y)              ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, tls_rn1,      'VN=tls_rn1      ;ON=RRN1;VD=pcp rate - liquid drizzle   (M-Y)              ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, tls_rn2,      'VN=tls_rn2      ;ON=RRN2;VD=pcp rate - liquid rain      (M-Y)              ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, tlwp,         'VN=tlwp         ;ON=ICR ;VD=total liquid water path for radiation          ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, tlwpin,       'VN=tlwpin       ;ON=W1  ;VD=total in-cloud liquid water path (Rockel)      ;VS=row                    ;VB=p0        ;MIN=0')
 if(lmoyhr)    call gesdict (n, nk, tlwpm,        'VN=tlwpm        ;ON=ICRM;VD=total LWP for rad avge over last moyhr hrs     ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, tmoins,       'VN=PW_TT:M      ;ON=T8  ;VD=temperature at t-dt                            ;VS=slc                    ;VB=d1')
               call gesdict (n, nk, topthi,       'VN=topthi       ;ON=W4  ;VD=total optical thickness of ice                 ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, topthw,       'VN=topthw       ;ON=W3  ;VD=total optical thickness of water               ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, tphytd,       'VN=phytd_tt     ;ON=TPHY;VD=total T tendency due to physics                ;VS=slc                    ;VB=v1')
 if(lmoyhr)    call gesdict (n, nk, tphytdm,      'VN=tphytdm      ;ON=TPHM;VD=total T physics tdcy avg over the moyhr hrs    ;VS=slc                    ;VB=p0')
               call gesdict (n, nk, tplus,        'VN=PW_TT:P      ;ON=2T  ;VD=temperature at t+dt                            ;VS=slc                    ;VB=d1;IN=TT')
               call gesdict (n, nk, tqcx,         'VN=tqcx         ;ON=TQCX;VD=QC tendency due to strat cond                  ;VS=slc                    ;VB=v0')
               call gesdict (n, nk, trad,         'VN=trad         ;ON=T3  ;VD=T tendency due to radiation                    ;VS=slc                    ;VB=v1')
               call gesdict (n, nk, tsc,          'VN=tsc          ;ON=P3  ;VD=solid convect. precip. rate                    ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, tscs,         'VN=tscs         ;ON=A6  ;VD=solid shall. convect. precip. rate             ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, tshal,        'VN=tshal        ;ON=ST  ;VD=T tendency due to shallow conv.                ;VS=slc                    ;VB=v0')
 if(lmoyhr)    call gesdict (n, nk, tshalm,       'VN=tshalm       ;ON=X6  ;VD=avg T tendency shal conv. over last moyhr hrs  ;VS=slc                    ;VB=p0')
               call gesdict (n, nk, tsrad,        'VN=tsrad        ;ON=TG  ;VD=radiative surface temperature                  ;VS=row@'//nm//'           ;VB=p0')
               call gesdict (n, nk, tss,          'VN=tss          ;ON=P4  ;VD=solid precip. rate, grid-scale cond            ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, tss_mx,       'VN=tss_mx       ;ON=RMX ;VD=pcp rate - mixed pcp         (M-Y)             ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, tss_pe1,      'VN=tss_pe1      ;ON=RPE1;VD=pcp rate - ice pellets      (M-Y)              ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, tss_pe2,      'VN=tss_pe2      ;ON=RPE2;VD=pcp rate - hail             (M-Y)              ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, tss_pe2l,     'VN=tss_pe2l     ;ON=RPEL;VD=pcp rate - large hail      (M-Y)               ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, tss_s2l,      'VN=tss_s2l      ;ON=RS2L;VD=inst. solid-to-liquid ratio (M-Y)              ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, tss_sn1,      'VN=tss_sn1      ;ON=RSN1;VD=pcp rate - ice crystals     (M-Y)              ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, tss_sn2,      'VN=tss_sn2      ;ON=RSN2;VD=pcp rate - snow             (M-Y)              ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, tss_sn3,      'VN=tss_sn3      ;ON=RSN3;VD=pcp rate - graupel          (M-Y)              ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, tss_snd,      'VN=tss_snd      ;ON=RSND;VD=pcp rt - solid total snow   (M-Y)              ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, tsurf,        'VN=tsurf        ;ON=J8  ;VD=area-averaged surf. temperature                ;VS=row@'//nm//'           ;VB=p0')
 if(lmoyhr)    call gesdict (n, nk, ttmax,        'VN=ttmax        ;ON=T9  ;VD=max temperature over last moyhr hrs            ;VS=slc                    ;VB=p0')
 if(lmoyhr)    call gesdict (n, nk, ttmin,        'VN=ttmin        ;ON=T5  ;VD=min temperature over last moyhr hrs            ;VS=slc                    ;VB=p0')
               call gesdict (n, nk, turbreg,      'VN=turbreg      ;ON=TURB;VD=turbulence regime for PBL scheme               ;VS=sls                    ;VB=p0')
               call gesdict (n, nk, tusc,         'VN=tusc         ;ON=TUSC;VD=U tendency due to SHAL BKF                     ;VS=slb                    ;VB=v0')
               call gesdict (n, nk, tve,          'VN=tve          ;ON=1J  ;VD=virtual temp. (stagg. levels)                  ;VS=sls                    ;VB=v0')
               call gesdict (n, nk, tvsc,         'VN=tvsc         ;ON=TVSC;VD=V tendency due to SHAL BKF                     ;VS=slb                    ;VB=v0')
               call gesdict (n, nk, uadv,         'VN=uadv         ;ON=UADV;VD=U advection tendency                           ;VS=slb                    ;VB=v1')
 if(lmoyhr)    call gesdict (n, nk, uadvm,        'VN=uadvm        ;ON=UADM;VD=U advection tend. avge over last moyhr hrs     ;VS=slb                    ;VB=p0')
 if(lmoyhrkf)  call gesdict (n, nk, udcm,         'VN=udcm         ;ON=UDCM;VD=avg U tend of deep conv over last moyhr hrs    ;VS=slb                    ;VB=p0')
               call gesdict (n, nk, udiag,        'VN=udiag        ;ON=UD  ;VD=screen level X-component of wind               ;VS=row@'//nm//'           ;VB=p0')
               call gesdict (n, nk, udifv,        'VN=udifv        ;ON=TU  ;VD=U tendency due to vert. diffusion              ;VS=slb                    ;VB=v1')
 if(lmoyhr)    call gesdict (n, nk, udifvm,       'VN=udifvm       ;ON=X2  ;VD=U dif. tend. avge over last moyhr hrs          ;VS=slb                    ;VB=p0')
               call gesdict (n, nk, ue,           'VN=ue           ;ON=UE  ;VD=friction velocity (from FQ)                    ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, ufcp,         'VN=ufcp         ;ON=U6  ;VD=U tendency due to FCP                          ;VS=slb                    ;VB=p1')
               call gesdict (n, nk, ugno,         'VN=ugno         ;ON=M1  ;VD=U tend. due to non-oro. gwd                    ;VS=slb                    ;VB=v1')
 if(lmoyhr)    call gesdict (n, nk, ugnom,        'VN=ugnom        ;ON=NOUM;VD=NOGW U tend. average over last moyhr hrs       ;VS=slb                    ;VB=p0')
               call gesdict (n, nk, ugwd,         'VN=phytd_ugwd   ;ON=GU  ;VD=U tendency due to gwd                          ;VS=slb                    ;VB=v1')
 if(lmoyhr)    call gesdict (n, nk, ugwdm,        'VN=ugwdm        ;ON=UG  ;VD=GWD U tend. average over last moyhr hrs        ;VS=slb                    ;VB=p0')
 if(lkfbe)     call gesdict (n, nk, umfkfc,       'VN=umfkfc       ;ON=K5  ;VD=updraft mass flux in KF                        ;VS=slc                    ;VB=p0        ;MIN=0')
 if(lmoyhrkf)  call gesdict (n, nk, umfkfcm,      'VN=umfkfcm      ;ON=4K  ;VD=avg umfkfc                                     ;VS=slc                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, umoins,       'VN=PW_UU:M      ;ON=U8  ;VD=wind speed along-x at t-dt                     ;VS=slb                    ;VB=d1')
               call gesdict (n, nk, uphytd,       'VN=phytd_uu     ;ON=UPHY;VD=total U tendency due to physics                ;VS=slb                    ;VB=v1')
               call gesdict (n, nk, uphytdm,      'VN=uphytdm      ;ON=UPHM;VD=total U physics tdcy avg over the moyhr hrs    ;VS=slb                    ;VB=p0')
               call gesdict (n, nk, uplus,        'VN=PW_UU:P      ;ON=UP  ;VD=wind speed along-x at t+dt                     ;VS=slb                    ;VB=d1;IN=UU')
 if(lmoyhrkf)  call gesdict (n, nk, uscm,         'VN=uscm         ;ON=USCM;VD=avg U tend of shall conv over last moyhr hrs   ;VS=slb                    ;VB=p0')
               call gesdict (n, nk, ustress,      'VN=ustress      ;ON=F3  ;VD=zonal surf. momentum flux                      ;VS=row                    ;VB=v0')
 if(lmoyhr)    call gesdict (n, nk, uvsavg,       'VN=uvsavg       ;ON=UVAV;VD=screen wind modulus average over l.moyhr hrs   ;VS=row                    ;VB=p0        ;MIN=0')
 if(lmoyhr)    call gesdict (n, nk, uvsmax,       'VN=uvsmax       ;ON=UVMX;VD=screen max wind modulus over last moyhr hours  ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, vadv,         'VN=vadv         ;ON=VADV;VD=V advection tendency                           ;VS=slb                    ;VB=v1')
 if(lmoyhr)    call gesdict (n, nk, vadvm,        'VN=vadvm        ;ON=VADM;VD=V advection tend. avge over last moyhr hrs     ;VS=slb                    ;VB=p0')
 if(lmoyhrkf)  call gesdict (n, nk, vdcm,         'VN=vdcm         ;ON=VDCM;VD=avg V tend of deep conv over last moyhr hrs    ;VS=slb                    ;VB=p0')
               call gesdict (n, nk, vdiag,        'VN=vdiag        ;ON=VD  ;VD=screen level Y-component of wind               ;VS=row@'//nm//'           ;VB=p0')
               call gesdict (n, nk, vdifv,        'VN=vdifv        ;ON=TV  ;VD=V tendency due to vert. diffusion              ;VS=slb                    ;VB=v1')
 if(lmoyhr)    call gesdict (n, nk, vdifvm,       'VN=vdifvm       ;ON=X3  ;VD=V dif. tend. avge over last moyhr hrs          ;VS=slb                    ;VB=p0')
               call gesdict (n, nk, vfcp,         'VN=vfcp         ;ON=V7  ;VD=V tendency due to FCP                          ;VS=slb                    ;VB=p1')
               call gesdict (n, nk, vgno,         'VN=vgno         ;ON=M2  ;VD=V tend. due to non-oro. gwd                    ;VS=slb                    ;VB=v1')
 if(lmoyhr)    call gesdict (n, nk, vgnom,        'VN=vgnom        ;ON=NOVM;VD=NOGW v tend. average over last moyhr hrs       ;VS=slb                    ;VB=p0')
               call gesdict (n, nk, vgwd,         'VN=phytd_vgwd   ;ON=GV  ;VD=V tendency due to gwd                          ;VS=slb                    ;VB=v1')
 if(lmoyhr)    call gesdict (n, nk, vgwdm,        'VN=vgwdm        ;ON=V6  ;VD=GWD V tend. average over last moyhr hrs        ;VS=slb                    ;VB=p0')
 if(lcn_my2)   call gesdict (n, nk, vis,          'VN=vis          ;ON=VIS ;VD=visibility (fog) from (microphy) [km]          ;VS=slc                    ;VB=v0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, vis1,         'VN=vis1         ;ON=VIS1;VD=vis1 though liquid fog (M-Y) [km]              ;VS=slc                    ;VB=v0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, vis2,         'VN=vis2         ;ON=VIS2;VD=vis through rain  (M-Y) [km]                   ;VS=slc                    ;VB=v0        ;MIN=0')
 if(lcn_my2)   call gesdict (n, nk, vis3,         'VN=vis3         ;ON=VIS3;VD=vis3 through snow (M-Y) [km]                   ;VS=slc                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, vmoins,       'VN=PW_VV:M      ;ON=V8  ;VD=wind speed along-y at t-dt                     ;VS=slb                    ;VB=d1')
               call gesdict (n, nk, vozo,         'VN=vozo         ;ON=VO  ;VD=trans. of ozone layer above model lid          ;VS=row                    ;VB=p0')
               call gesdict (n, nk, vphytd,       'VN=phytd_vv     ;ON=VPHY;VD=total V tendency due to physics                ;VS=slb                    ;VB=v1')
               call gesdict (n, nk, vphytdm,      'VN=vphytdm      ;ON=VPHM;VD=total V physics tdcy avg over the moyhr hrs    ;VS=slb                    ;VB=p0')
               call gesdict (n, nk, vplus,        'VN=PW_VV:P      ;ON=VP  ;VD=wind speed along-y at t+dt                     ;VS=slb                    ;VB=d1;IN=VV')
 if(lmoyhrkf)  call gesdict (n, nk, vscm,         'VN=vscm         ;ON=VSCM;VD=avg V tend of shall conv over last moyhr hrs   ;VS=slb                    ;VB=p0')
               call gesdict (n, nk, vstress,      'VN=vstress      ;ON=F2  ;VD=meridional surf. momentum flux                 ;VS=row                    ;VB=v0')
               call gesdict (n, nk, vv1,          'VN=vv1          ;ON=VV1 ;VD=solar renormalization factor                   ;VS=row                    ;VB=p0')
 if(diffuw)    call gesdict (n, nk, wdifv,        'VN=wdifv        ;ON=WI  ;VD=W tendency due to vert. diffusn                ;VS=slc                    ;VB=v0')
               call gesdict (n, nk, wge,          'VN=wge          ;ON=WGE ;VD=wind gust estimate                             ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, wgmax,        'VN=wgmax        ;ON=WGX ;VD=wind gust maximum                              ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, wgmin,        'VN=wgmin        ;ON=WGN ;VD=wind gust minimum                              ;VS=row                    ;VB=v0        ;MIN=0')
 if(diffuw)    call gesdict (n, nk, wphytd,       'VN=phytd_ww     ;ON=WPHY;VD=total W tendency due to physics                ;VS=slc                    ;VB=v1')
               call gesdict (n, nk, wplus,        'VN=PW_WZ:P      ;ON=WP  ;VD=wind speed along-z at t+dt                     ;VS=slc                    ;VB=d'//need_wz//' ; IN=WW')

               call gesdict (n, nk, wstar,        'VN=wstar        ;ON=WSTA;VD=convective velocity scale                      ;VS=row                    ;VB=v0        ;MIN=0')
 if(lkfbe)     call gesdict (n, nk, wumaxkfc,     'VN=wumaxkfc     ;ON=K6  ;VD=max upward velocity in KF                      ;VS=row                    ;VB=p0        ;MIN=0')
 if(lmoyhrkf)  call gesdict (n, nk, wumkfcm,      'VN=wumkfcm      ;ON=7K  ;VD=avg wumaxkfc                                   ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, xcent,        'VN=xcent        ;ON=Y5  ;VD=unresolv topo eccentricity                     ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, z0,           'VN=z0           ;ON=Z0  ;VD=momentum roughness length                      ;VS=row*'//nagg//'@'//nm//';VB=p0        ;MIN=0')
               call gesdict (n, nk, z0t,          'VN=z0t          ;ON=ZT  ;VD=thermal roughness length                       ;VS=row*'//nagg//'@'//nm//';VB=p0        ;MIN=0')
               call gesdict (n, nk, z1,           'VN=z1           ;ON=Z1  ;VD=dir. roughness length (+x)                     ;VS=row                    ;VB=p0')
               call gesdict (n, nk, z2,           'VN=z2           ;ON=Z2  ;VD=dir. roughness length (-x)                     ;VS=row                    ;VB=p0')
               call gesdict (n, nk, z3,           'VN=z3           ;ON=Z3  ;VD=dir. roughness length (+y)                     ;VS=row                    ;VB=p0')
               call gesdict (n, nk, z4,           'VN=z4           ;ON=Z4  ;VD=dir. roughness length (-y)                     ;VS=row                    ;VB=p0')
               call gesdict (n, nk, za,           'VN=za           ;ON=ZA  ;VD=thickness of the surface layer                 ;VS=row                    ;VB=v0        ;MIN=0')
 if(lkfbe)     call gesdict (n, nk, zbasekfc,     'VN=zbasekfc     ;ON=U9  ;VD=cloud base height in KF                        ;VS=row                    ;VB=p0        ;MIN=0')
 if(lmoyhrkf)  call gesdict (n, nk, zbaskfcm,     'VN=zbaskfcm     ;ON=8K  ;VD=avg zbasekfc                                   ;VS=row                    ;VB=p0        ;MIN=0')
 if(lmoyhr)    call gesdict (n, nk, zcqcem,       'VN=zcqcem       ;ON=X1  ;VD=QC conv. tend. avge over last moyhr hrs        ;VS=slc                    ;VB=p0')
 if(lmoyhr)    call gesdict (n, nk, zcqem,        'VN=zcqem        ;ON=W8  ;VD=HU conv. tend. avge over last moyhr hrs        ;VS=slc                    ;VB=p0')
 if(lmoyhr)    call gesdict (n, nk, zctem,        'VN=zctem        ;ON=W6  ;VD=T conv. tend. avge over last moyhr hrs         ;VS=slc                    ;VB=p0')
               call gesdict (n, nk, zd,           'VN=zd           ;ON=ZD  ;VD=length scale of dissipation                    ;VS=sls                    ;VB=p0        ;MIN=0')
 if(lcn_mpx)   call gesdict (n, nk, zec,          'VN=zec          ;ON=ZEC ;VD=composite of reflectivity                      ;VS=row                    ;VB=v0')
 if(lcn_mpx)   call gesdict (n, nk, zet,          'VN=zet          ;ON=ZET ;VD=total equivalent reflectivity                  ;VS=slc                    ;VB=v0')
               call gesdict (n, nk, zn,           'VN=zn           ;ON=ZN  ;VD=mixing length of turbulence                    ;VS=sls                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, zrflag,       'VN=zrflag       ;ON=ZF  ;VD=Presence of freesing rain 0 or 1               ;VS=row                    ;VB=v0')
 if(lmoyhr)    call gesdict (n, nk, zsqcem,       'VN=zsqcem       ;ON=W5  ;VD=QC strat. tend. avge over last moyhr hrs       ;VS=slc                    ;VB=p0')
 if(lmoyhr)    call gesdict (n, nk, zsqem,        'VN=zsqem        ;ON=W9  ;VD=HU strat. tend. avge over last moyhr hrs       ;VS=slc                    ;VB=p0')
 if(lmoyhr)    call gesdict (n, nk, zstem,        'VN=zstem        ;ON=W7  ;VD=T strat. tend. avge over last moyhr hrs        ;VS=slc                    ;VB=p0')
 if(lkfbe)     call gesdict (n, nk, ztopkfc,      'VN=ztopkfc      ;ON=K4  ;VD=cloud top height in KF                         ;VS=row                    ;VB=p0        ;MIN=0')
 if(lmoyhrkf)  call gesdict (n, nk, ztopkfcm,     'VN=ztopkfcm     ;ON=9K  ;VD=avg ztopkfc                                    ;VS=row                    ;VB=p0        ;MIN=0')
               call gesdict (n, nk, ztsl,         'VN=ztsl         ;ON=ZH  ;VD=temperature level at top of surface layer      ;VS=row                    ;VB=v0        ;MIN=0')
               call gesdict (n, nk, zusl,         'VN=zusl         ;ON=ZU  ;VD=wind level at top of surface layer             ;VS=row                    ;VB=v0        ;MIN=0')

 if(lightning_diag) call gesdict (n, nk, afoudre, 'VN=afoudre      ;ON=FDAC;VD=accumulated lightning threat from microphysics ;VS=row                    ;VB=p0        ;MIN=0')
 if(lightning_diag) call gesdict (n, nk, foudre,  'VN=foudre       ;ON=FDRE;VD=lightning threat from microphysics             ;VS=row                    ;VB=p0        ;MIN=0')
 if(lcn_my2)  call gesdict (n, nk, ncmoins,      'VN=TR/mpnc:M,min=0    ;ON=MMNC;VD=microphysics, num. mix. ratio (t-dT),   cloud  ;VS=slc               ;VB=d1')
 if(lcn_my2)  call gesdict (n, nk, ncphytd,      'VN=phytd_mpnc   ;ON=MTNC;VD=microphysics, num. mix. ratio tendency, cloud  ;VS=slc                     ;VB=v0')
 if(lcn_my2)  call gesdict (n, nk, ncplus,       'VN=TR/mpnc:P,min=0    ;ON=MPNC;VD=microphysics, num. mix. ratio (t+dT),   cloud  ;VS=slc               ;VB=d1;IN=MPNC')
 if(lcn_my2)  call gesdict (n, nk, ngmoins,      'VN=TR/mpng:M,min=0    ;ON=MMNG;VD=microphysics, num. mix. ratio (t-dT),   graupel;VS=slc               ;VB=d1')
 if(lcn_my2)  call gesdict (n, nk, ngphytd,      'VN=phytd_mpng   ;ON=MTNG;VD=microphysics, num. mix. ratio tendency, graupel;VS=slc                     ;VB=v0')
 if(lcn_my2)  call gesdict (n, nk, ngplus,       'VN=TR/mpng:P,min=0    ;ON=MPNG;VD=microphysics, num. mix. ratio (t+dT),   graupel;VS=slc               ;VB=d1;IN=MPNG')
 if(lcn_my2)  call gesdict (n, nk, nhmoins,      'VN=TR/mpnh:M,min=0    ;ON=MMNH;VD=microphysics, num. mix. ratio (t-dT),   hail   ;VS=slc               ;VB=d1')
 if(lcn_my2)  call gesdict (n, nk, nhphytd,      'VN=phytd_mpnh   ;ON=MTNH;VD=microphysics, num. mix. ratio tendency, hail   ;VS=slc                     ;VB=v0')
 if(lcn_my2)  call gesdict (n, nk, nhplus,       'VN=TR/mpnh:P,min=0    ;ON=MPNH;VD=microphysics, num. mix. ratio (t+dT),   hail   ;VS=slc               ;VB=d1;IN=MPNH')
 if(lcn_my2)  call gesdict (n, nk, nimoins,      'VN=TR/mpni:M,min=0    ;ON=MMNI;VD=microphysics, num. mix. ratio (t-dT),   ice    ;VS=slc               ;VB=d1')
 if(lcn_my2)  call gesdict (n, nk, niphytd,      'VN=phytd_mpni   ;ON=MTNI;VD=microphysics, num. mix. ratio tendency, ice    ;VS=slc                     ;VB=v0')
 if(lcn_my2)  call gesdict (n, nk, niplus,       'VN=TR/mpni:P,min=0    ;ON=MPNI;VD=microphysics, num. mix. ratio (t+dT),   ice    ;VS=slc               ;VB=d1;IN=MPNI')
 if(lcn_my2)  call gesdict (n, nk, nnmoins,      'VN=TR/mpns:M,min=0    ;ON=MMNS;VD=microphysics, num. mix. ratio (t-dT),   snow   ;VS=slc               ;VB=d1')
 if(lcn_my2)  call gesdict (n, nk, nnphytd,      'VN=phytd_mpns   ;ON=MTNS;VD=microphysics, num. mix. ratio tendency, snow   ;VS=slc                     ;VB=v0')
 if(lcn_my2)  call gesdict (n, nk, nnplus,       'VN=TR/mpns:P,min=0    ;ON=MPNS;VD=microphysics, num. mix. ratio (t+dT),   snow   ;VS=slc               ;VB=d1;IN=MPNS')
 if(lcn_mpx)  call gesdict (n, nk, nrmoins,      'VN=TR/mpnr:M,min=0    ;ON=MMNR;VD=microphysics, num. mix. ratio (t-dT),   rain   ;VS=slc               ;VB=d1')
 if(lcn_mpx)  call gesdict (n, nk, nrphytd,      'VN=phytd_mpnr   ;ON=MTNR;VD=microphysics, num. mix. ratio tendency, rain   ;VS=slc                     ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, nrplus,       'VN=TR/mpnr:P,min=0    ;ON=MPNR;VD=microphysics, num. mix. ratio (t+dT),   rain   ;VS=slc               ;VB=d1;IN=MPNR')

 if(lcn_mpx)  call gesdict (n, nk, qcmoins,      'VN=TR/mpqc:M,wload=1,min=0  ;ON=MMQC;VD=microphysics, mass mix. ratio (t-dT),   cloud  ;VS=slc         ;VB=d1')
 if(lcn_mpx)  call gesdict (n, nk, qcphytd,      'VN=phytd_mpqc         ;ON=MTQC;VD=microphysics, mass mix. ratio tendency, cloud  ;VS=slc               ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, qcplus,       'VN=TR/mpqc:P,wload=1,min=0  ;ON=MPQC;VD=microphysics, mass mix. ratio (t+dT),   cloud  ;VS=slc         ;VB=d1;IN=MPQC')
 if(lcn_my2)  call gesdict (n, nk, qgmoins,      'VN=TR/mpqg:M,wload=1,min=0  ;ON=MMQG;VD=microphysics, mass mix. ratio (t-dT),   graupel;VS=slc         ;VB=d1')
 if(lcn_my2)  call gesdict (n, nk, qgphytd,      'VN=phytd_mpqg         ;ON=MTQG;VD=microphysics, mass mix. ratio tendency, graupel;VS=slc               ;VB=v0')
 if(lcn_my2)  call gesdict (n, nk, qgplus,       'VN=TR/mpqg:P,wload=1,min=0  ;ON=MPQG;VD=microphysics, mass mix. ratio (t+dT),   graupel;VS=slc         ;VB=d1;IN=MPQG')
 if(lcn_my2)  call gesdict (n, nk, qhmoins,      'VN=TR/mpqh:M,wload=1,min=0  ;ON=MMQH;VD=microphysics, mass mix. ratio (t-dT),   hail   ;VS=slc         ;VB=d1')
 if(lcn_my2)  call gesdict (n, nk, qhphytd,      'VN=phytd_mpqh         ;ON=MTQH;VD=microphysics, mass mix. ratio tendency, hail   ;VS=slc               ;VB=v0')
 if(lcn_my2)  call gesdict (n, nk, qhplus,       'VN=TR/mpqh:P,wload=1,min=0  ;ON=MPQH;VD=microphysics, mass mix. ratio (t+dT),   hail   ;VS=slc         ;VB=d1;IN=MPQH')
 if(lcn_my2)  call gesdict (n, nk, qimoins,      'VN=TR/mpqi:M,wload=1,min=0  ;ON=MMQI;VD=microphysics, mass mix. ratio (t-dT),   ice    ;VS=slc         ;VB=d1')
 if(lcn_my2)  call gesdict (n, nk, qiphytd,      'VN=phytd_mpqi         ;ON=MTQI;VD=microphysics, mass mix. ratio tendency, ice    ;VS=slc               ;VB=v0')
 if(lcn_my2)  call gesdict (n, nk, qiplus,       'VN=TR/mpqi:P,wload=1,min=0  ;ON=MPQI;VD=microphysics, mass mix. ratio (t+dT),   ice    ;VS=slc         ;VB=d1;IN=MPQI')
 if(lcn_my2)  call gesdict (n, nk, qnmoins,      'VN=TR/mpqs:M,wload=1,min=0  ;ON=MMQS;VD=microphysics, mass mix. ratio (t-dT),   snow   ;VS=slc         ;VB=d1')
 if(lcn_my2)  call gesdict (n, nk, qnphytd,      'VN=phytd_mqns         ;ON=MTQS;VD=microphysics, mass mix. ratio tendency, snow   ;VS=slc               ;VB=v0')
 if(lcn_my2)  call gesdict (n, nk, qnplus,       'VN=TR/mpqs:P,wload=1,min=0  ;ON=MPQS;VD=microphysics, mass mix. ratio (t+dT),   snow   ;VS=slc         ;VB=d1;IN=MPQS')
 if(lcn_mpx)  call gesdict (n, nk, qrmoins,      'VN=TR/mpqr:M,wload=1,min=0  ;ON=MMQR;VD=microphysics, mass mix. ratio (t-dT),   rain   ;VS=slc         ;VB=d1')
 if(lcn_mpx)  call gesdict (n, nk, qrphytd,      'VN=phytd_mpqr         ;ON=MTQR;VD=microphysics, mass mix. ratio tendency, rain   ;VS=slc               ;VB=v0')
 if(lcn_mpx)  call gesdict (n, nk, qrplus,       'VN=TR/mpqr:P,wload=1,min=0  ;ON=MPQR;VD=microphysics, mass mix. ratio (t+dT),   rain   ;VS=slc         ;VB=d1;IN=MPQR')

 if(lcn_p3i1)  call gesdict (n, nk, i1qtplus,   'VN=TR/i1qt:P,wload=1,min=0 ;ON=QI   ;VD=total mass, ice cat 1 (P3), t+dT        ;VS=slc                 ;VB=d1;IN=I1QT')
 if(lcn_p3i1)  call gesdict (n, nk, i1qmplus,   'VN=TR/i1qm:P,min=0      ;ON=5M   ;VD=rime mass, ice cat 1 (P3), t+dT         ;VS=slc                    ;VB=d1;IN=I1QM')
 if(lcn_p3i1)  call gesdict (n, nk, i1ntplus,   'VN=TR/i1nt:P,min=0      ;ON=3M   ;VD=total number, ice cat 1 (P3), t+dT      ;VS=slc                    ;VB=d1;IN=I1NT')
 if(lcn_p3i1)  call gesdict (n, nk, i1bvplus,   'VN=TR/i1bv:P,min=0      ;ON=6M   ;VD=bulk volume, ice cat 1 (P3), t+dT       ;VS=slc                    ;VB=d1;IN=I1BV')

 if(lcn_p3i2)  call gesdict (n, nk, i2qtplus,   'VN=TR/i2qt:P,wload=1,min=0 ;ON=QI2  ;VD=total mass, ice cat 2 (P3), t+dT        ;VS=slc                 ;VB=d1;IN=I2QT')
 if(lcn_p3i2)  call gesdict (n, nk, i2qmplus,   'VN=TR/i2qm:P,min=0      ;ON=5M2  ;VD=rime mass, ice cat 2 (P3), t+dT         ;VS=slc                    ;VB=d1;IN=I2QM')
 if(lcn_p3i2)  call gesdict (n, nk, i2ntplus,   'VN=TR/i2nt:P,min=0      ;ON=3M2  ;VD=total number, ice cat 2 (P3), t+dT      ;VS=slc                    ;VB=d1;IN=I2NT')
 if(lcn_p3i2)  call gesdict (n, nk, i2bvplus,   'VN=TR/i2bv:P,min=0      ;ON=6M2  ;VD=bulk volume, ice cat 2 (P3), t+dT       ;VS=slc                    ;VB=d1;IN=I2BV')

 if(lcn_p3i3)  call gesdict (n, nk, i3qtplus,   'VN=TR/i3qt:P,wload=1,min=0 ;ON=QI3  ;VD=total mass, ice cat 3 (P3), t+dT        ;VS=slc                 ;VB=d1;IN=I3QT')
 if(lcn_p3i3)  call gesdict (n, nk, i3qmplus,   'VN=TR/i3qm:P,min=0      ;ON=5M3  ;VD=rime mass, ice cat 3 (P3), t+dT         ;VS=slc                    ;VB=d1;IN=I3QM')
 if(lcn_p3i3)  call gesdict (n, nk, i3ntplus,   'VN=TR/i3nt:P,min=0      ;ON=3M3  ;VD=total number, ice cat 3 (P3), t+dT      ;VS=slc                    ;VB=d1;IN=I3NT')
 if(lcn_p3i3)  call gesdict (n, nk, i3bvplus,   'VN=TR/i3bv:P,min=0      ;ON=6M3  ;VD=bulk volume, ice cat 3 (P3), t+dT       ;VS=slc                    ;VB=d1;IN=I3BV')

 if(lcn_p3i4)  call gesdict (n, nk, i4qtplus,   'VN=TR/i4qt:P,wload=1,min=0 ;ON=QI4  ;VD=total mass, ice cat 4 (P3), t+dT        ;VS=slc                 ;VB=d1;IN=I4QT')
 if(lcn_p3i4)  call gesdict (n, nk, i4qmplus,   'VN=TR/i4qm:P,min=0      ;ON=5M4  ;VD=rime mass, ice cat 4 (P3), t+dT         ;VS=slc                    ;VB=d1;IN=I4QM')
 if(lcn_p3i4)  call gesdict (n, nk, i4ntplus,   'VN=TR/i4nt:P,min=0      ;ON=3M4  ;VD=total number, ice cat 4 (P3), t+dT      ;VS=slc                    ;VB=d1;IN=I4NT')
 if(lcn_p3i4)  call gesdict (n, nk, i4bvplus,   'VN=TR/i4bv:P,min=0      ;ON=6M4  ;VD=bulk volume, ice cat 4 (P3), t+dT       ;VS=slc                    ;VB=d1;IN=I4BV')

              call gesdict (n, nk, me_moins,     'VN=PW_ME:M      ;ON=MEM ;VD=driver topography at t-dt                      ;VS=row                    ;VB=d1')
              call gesdict (n, nk, p0_moins,     'VN=PW_P0:P      ;ON=P0M ;VD=driver surface pressure at t-dt                ;VS=row                    ;VB=d1        ;MIN=0')

   call sfc_businit(moyhr,n,nk)

   call chm_businit(n,nk)

   return
end subroutine phybusinit
